<a href="https://colab.research.google.com/github/idoschw3/Corpus2GeoRAG/blob/main/ApplyNER/NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
from transformers import pipeline
from google.colab import userdata
import pandas as pd
import numpy as np
import subprocess
import json
import os

### Clone Corpus2GeoRAG Repository

In [81]:
%%bash
rm -rf Corpus2GeoRAG
git clone https://github.com/EtzionR/Corpus2GeoRAG.git

Cloning into 'Corpus2GeoRAG'...

### Data Loading and Initial Inspection

**Purpose:** To load the raw text data, which is crucial for subsequent NER tasks, from a JSON file. This section also includes an example to visually inspect the structure and content of a single entry, ensuring the data is correctly loaded and accessible.


**Input/Output:** Input is `/content/Corpus2GeoRAG/examples/DATA.json`.

**Date:** 2026-09-23

In [82]:
PATH = r'/content/Corpus2GeoRAG/examples/DATA.json'
PATH

'/content/Corpus2GeoRAG/examples/DATA.json'

In [83]:
with open(PATH, 'r') as file:
    data = json.load(file)

len(data)

897

In [84]:
[*data.keys()][:10]

['12 (song)',
 '14 May 2026 Russian strikes on Ukraine',
 '15th BRICS summit',
 '16 March 2022 Chernihiv breadline attack',
 '17 November 2024 Russian strikes on Ukraine',
 '18 March 2022 Mykolaiv military quarters attack',
 '1st European Political Community Summit',
 '2000 Meters to Andriivka',
 '2014 pro-Russian unrest in Ukraine',
 '2020s European re-armament']

In [85]:
example = np.random.choice([*data],1)[0]


print(f'PAGE: {example}:\n\n{data[example]}')

PAGE: Boycott of Russia and Belarus:

Since early 2022, Russia and Belarus have been boycotted by many companies and organizations in Europe, North America, Australasia, and elsewhere, in response to the Russian invasion of Ukraine, which is supported by Belarus. As of 2 July 2022, the Yale School of Management recorded more than 1,000 companies withdrawing or divesting themselves from Russia, either as a result of sanctions or in protest of Russian actions. Ukrainian National Agency on Corruption Prevention maintains a list called International Sponsors of War that includes companies and individuals still doing business with Russia.


== Overview ==
The majority of countries which sanctioned Russia following its 2014 annexation of Crimea began imposing additional sanctions to punish Russia for invading Ukraine—a move for which Russian President Vladimir Putin had long prepared. Many companies were not impacted by sanctions against Russia but ruled in favour of cutting ties with the country either due to the public pressure or in protest of the Russian government's actions, or both. Ukrainian institutions have stated that the need for these measures is urgent.
The response can be broadly divided into a "cultural boycott", aimed at amplifying the international condemnation of the invasion, and an "economic boycott", which is designed to make the war effort less sustainable. As a result of the latter, several commentators have warned of an unprecedented economic collapse in Russia's future, citing a 30% drop in the ruble's value, a 20% rise in interest rates and a 1% GDP expansion down from 1.7%. Analyses by multiple firms project year end GDP contraction of at least 5% and inflation of 15%. Some of the most critical blows to Russian infrastructure have been the loss of access to the SWIFT payment system and limitations on Russia's ability to export oil. US Senator Bernie Sanders has stated that this crisis should influence energy policy more broadly in order to deter "authoritarian petrostates". While Shell plc has been noted for relinquishing its stake in Gazprom, it was also criticised for buying a cargo of discounted Russian crude oil. The next day, following public outcry, Shell defended the purchase as a short term necessity, but also announced that it intends to reduce such purchases and put the profits from them into a fund that will go towards humanitarian aid to Ukraine. As of 10 March, half of the ten largest international companies with business ties to Russia announced that they are withdrawing or closing their operations; and the number of companies that have done so is over 300.
Some of the largest snack and fast food companies have faced criticism for continuing to do business in Russia and Belarus. Anthony Pompliano has defended cryptocurrency trading platforms for not participating in the boycott, stating "there is an incredible amount of inhumanity that goes into the decision to cut off the average citizen from the global financial system. What was their crime?" Critics of the Israeli government have pointed out that several American politicians who support isolating Russia economically previously campaigned for and passed anti-BDS laws punishing boycotts of Israel.
The cultural side of the boycott has focused on reducing the number of entertainment products available to people in Russia. These include films and albums but also live televised events that are hosted in Western countries. Yasmeen Serhan has commented that nationalistic sentiment, which has historically benefited Putin's regime, will be undermined by Russia's exclusion from sporting events. The banning of Russia and Belarus from the Olympics has drawn comparisons to the athletic boycott of apartheid South Africa. According to Olympic historians David Wallechinsky and Bill Mallon, the decision can be considered a turning point when compared to past leniency over the state-sponsored doping programme in Russia or the attempted abduction of Krystsina Tsimanouskaya by Belarus.
In addition to cancelling planned appearances in Russia, several entertainment organisations with Russian members began to scrutinise their past support for Putin. Some of these celebrities refused to condemn the war but others lost their contracts because they did so without mentioning Putin by name. A statement by Alex Ovechkin, for example, called for peace in general and mentioned that his family members in Russia were also in danger. However, Czech former Detroit Red Wings and Ottawa Senators goaltender Dominik Hašek responded to Ovechkin and criticized him for his past support of Putin, stating "What!? Not only an alibist, a chicken shit, but also a liar!", while also calling on the NHL to suspend all Russian players. One musician who referred to his family's safety when condemning the war was Alexander Malofeev. The Vancouver Recital Society, which had begun requiring this of all Russian performers, responded that Malofeev's statement was not sufficient to allow his concert to go ahead.
Despite ongoing sanctions, 47 of the world's biggest 200 companies still have not left Russia, particularly energy companies remain invested there. U.K. energy giant Shell and Japanese trading firms Mitsui and Mitsubishi hold double-digit stakes in the Sakhalin-2 oil and natural gas project. On July 1, 2022, Putin signed a decree to allow the government to seize the Sakhalin-2 oil and natural gas project but further attempts to formally nationalize the assets of international firms were paused when the bill did not make it through the State Duma before the 2022 summer recess.  According to Western analysts, remaining companies have experienced expropriation and nationalization pressures, but officially Russia has denied that it is interested in such actions. In August 2022, Russia's trade and industry minister Denis Manturov stated, "we are not interested in the nationalization of enterprises or their removal.”


== Boycotting companies and organisations ==


=== Banking and finance ===


==== Other ====
The Church of England announced on 25 February it will sell £20m in Russian holdings held by its Church Commissioners and the Church of England Pensions Board. The church also said it would not make any further investments in Russia, calling it an "immoral flood of corrupt money".


=== Education, research and science ===


=== Energy ===


=== Entertainment ===


=== Video games and esports ===


=== Food and beverage ===


=== Goods ===


==== Automotive ====


==== Apparel and accessories ====


==== Other ====


=== Services ===


=== Shipping and transport ===


==== Aviation ====


==== Space ====
Continued international collaboration on missions to the International Space Station (ISS) has been thrown into doubt.
A petition to withdraw international support from Russian satellite navigation system GLONASS and boycott the platform has been proposed by Polish engineer Daniel Kucharski from  University of Texas at Austin and signed by tens of thousands of individuals. It is now being considered by ILRS.


=== Sports ===
Full boycotts

Partial boycotts

Broadcasting rights
The English Premier League announced that they will cancel its broadcast rights with Russian television network Match which supposed to be started in the 2022/23 season, its current broadcaster Okko Sport will end the rights to the league earlier.


=== Technology ===


=== Tourism and hospitality ===


== Other ==


=== Airspace closures ===

By 5 March 2022, the following countries and territories had completely closed their airspace to all Russian airlines and Russian-registered private jets:

The European Union had already banned all Belarusian aircraft from EU airspace in June 2021 in response to the forced landing of Ryanair Flight 4978.
As well, airlines from many other countries have diverted their flights away from Russian airspace, despite not being banned by Russia or not slapping a ban on Russian aircraft. This includes:

 Australia
 Bangladesh
 Hong Kong (Except flights to/from New York, Boston or Toronto, but would be unable to divert to Russian airports)
 Japan
 South Korea
 Singapore (Singapore Airlines had already diverted their flights away from Belarus after Ryanair Flight 4978 incident)
 Taiwan


=== Breaking of diplomatic relations ===
Both Ukraine and the Federated States of Micronesia indefinitely severed all diplomatic ties with Russia.


== Controversy ==


=== Criticism ===
Critics of the boycott and sanctions have predicted that they would not cause significant changes in the Russian government's policy. Patrick Cockburn argued that sanctions similar to those used against Iraq will cause widespread poverty and claim more lives than the use of military force. Others have supported the cultural boycott but called for economic coercion to be narrowly targeted. Some critics noted that the decision of major credit card companies to suspend their operations in Russia will affect any Russian who has taken out a credit card in their home country, including those who have protested against the war in Ukraine, who are trying to flee Russia or are now living abroad.
Activists in Russia believe that amid lost access to financial and educational institutions, Putin will be better able to paint Western countries as the enemy. Carnegie Moscow Center scholar Andrey Movchan wrote that sanctions aimed at ordinary Russians could be "exactly what the Kremlin wants – that tens of millions of Russians who oppose the regime will be unable to leave the country and even temporarily find themselves in a world free of Russian propaganda", stating that sanctions should instead "uncompromisingly block the Kremlin's access to its financial and technological resources".
Cloudflare CEO Matthew Prince stated that "if Cloudflare were to stop operating in Russia, the Russian government would celebrate us shutting down" because "indiscriminately terminating service would do little to harm the Russian government, but would both limit access to information outside the country, and make significantly more vulnerable those who have used us to shield themselves as they have criticized the government".
Regarding the cultural boycott, Patrick West wrote that many parts had become a vehicle for Russophobia, notably an incident in which the University of Milano-Bicocca in Italy considered cancelling a course on Dostoyevski but ultimately did not. A decision by the Cardiff Philharmonic Orchestra to cancel a planned performance of Tchaikovsky's 1812 Overture was met with similar controversy. One of the directors stated that continuing with the original concert would have been offensive due to the themes of Russian military pride and not simply because Tchaikovsky was Russian. Discussing these issues, the communications coordinator for Diem25 expressed regret that Netflix was suspending its adaptation of Anna Karenina due to the involvement of a Russian production company. Business professor Stanislav Markus has suggested that boycotts of Russia might expand to include more countries as the companies involved become increasingly comfortable with deglobalisation.


=== Polling within Russia and Belarus ===

In April 2022, only 11% of Belarusians supported sending Belarusian troops to Ukraine. A study performed by Chatham House in May 2022 revealed that 32% of Belarusian respondents supported the Russian invasion of Ukraine and 40% did not support the invasion.
A Kremlin-associated poll claimed that the 68% of the Russian population approves of the "special military operation" in Ukraine, while independent polls put that number at 58%. The Kremlin-associated poll, which was conducted between February 28 and March 6, claimed that Putin's approval rating was 74.6%. According to the poll, in the group of 18-to-24-year-olds, only 29% of Russians supported the "special military operation" in Ukraine. Two reasons many Russians still support Putin and the "special military operation" in Ukraine have to do with the propaganda and disinformation being sown by the Kremlin, and the antagonization and discrimination by Western populations/institutions of Russian people. Some Russians publicly displayed the infamous "Z" letter. Russian gymnast Ivan Kuliak displayed it while standing on a victory podium near a Ukrainian athlete and later expressed no regret for doing that. More than 200,000 attended Vladimir Putin's pro-war nationalist rally at the Luzhniki Stadium on 18 March, with many forced by their employers to attend.
A series of four online polls of Moscow residents by Alexei Navalny's Anti-Corruption Foundation claimed that between February 25 and March 3, the share of respondents in Moscow who considered Russia an "aggressor" increased from 29% to 53%, while the share of those who considered Russia a "peacemaker" fell by half from 25% to 12%.
Some observers noted what they described as a "generational struggle" among Russians over perception of the war, with younger Russians generally opposed to the war and older Russians more likely to accept the narrative presented by state-controlled media in Russia, the main source of news for most Russians. Kataryna Wolczuk, an associate fellow of Chatham House's Russia and Eurasia programme, said that "[Older] Russians are inclined to think in line with the official 'narrative' that Russia is defending Russian speakers in Ukraine, so it's about offering protection rather than aggression." A poll by the independent Levada Center published on 30 March saw Putin's approval rating jump from 71% in February to 83% in March. However, many respondents do not want to answer pollsters' questions for fear of negative consequences. In March 2022, when a Russian politician Maxim Katz and a group of Russian researchers commissioned a poll on Russians’ attitudes toward the war in Ukraine, 29,400 of the 31,000 people they called refused to answer after hearing the theme of the question.


=== Companies criticised for not joining the boycott ===
A number of companies have faced growing pressure to halt operations in Russia, but have not yet done so. Those include:

Accor, a French hospitality company with 55 locations in Russia
AmerisourceBergen, an American healthcare company with research depots in Russia
Arconic, an American industrial company
Binance, one of world's largest crypto exchanges, which refused to ban all Russian accounts. However, Binance announced that it has donated more than $10 million to its Ukrainian Emergency Relief Fund and $2.5 million to UNICEF's efforts in Ukraine.
Bosch, one of the largest German multinational engineering and technology companies headquartered in Gerlingen
Bridgestone, a Japanese auto and truck parts manufacturer, left Russia after it sold all its interests in December 2023.
Burger King, an American fast food chain
Citigroup, an American bank
COSCO, a Chinese container shipping company, and one of the largest container shipping companies in the world
Credit Suisse, a global investment bank and financial services firm founded and based in Switzerland. Credit Suisse has declared that its Moscow offices remain open, as it was trying to shred evidence of $1.7 billion Russian loans backed by yachts.
Deutsche Bank, a German multinational investment bank and financial services company headquartered in Frankfurt, Germany, and dual-listed on the FWB and the NYSE. According to The New Yorker, Deutsche Bank has long had an "abject" reputation among major banks, as it has been involved in major scandals across different issue areas.
Ferragamo, an Italian luxury goods company, does not own stores in Russia and shipments to franchise operations ceased in March 2022.
French retail companies owned wholly or partially by members of the Mulliez family:
Auchan, a supermarket chain which in 2016 was ranked first in a list of the largest foreign-owned companies by the Russian edition of Forbes, with revenue in Russia of more than $5 billion
Leroy Merlin, a home improvement and DIY retailer, operates 112 stores in Russia. On 11 March the company announced it had no plans to reduce its operations in Russia.
Herbalife, an American marketing company
International Paper, an American paper and pulp manufacturer
Japan Tobacco International, the top tobacco company in Russia, which controls 37% of the Russian tobacco market
Kia, a South Korean car manufacturer and Russia's third-largest carmaker as of 2016. Kia holds a 30% stake in the Hyundai Motor Manufacturing Rus plant in St. Petersburg which is being sold in December 2023. The contract includes a two-year buyback clause.
Kimberly-Clark, an American personal care corporation
Koch Industries, an American conglomerate
Lenovo, a Chinese hardware and electronics manufacturer
Metro AG, a German company which operates cash and carry stores in Russia
Micro-Star International, a Taiwanese multinational information technology corporation
Mohawk Industries, an American manufacturer
Nokian Tyres, which produces 80% of its tyres in Russia and employs around 1,600 people. In October 2022, Nokian sold its Russian operations to Tatneft for €400 million and announced a €650 million investment for a new factory in Romania.
Otis Worldwide, an American elevator and escalator manufacturer. It announced on 11 March that is suspending new sales of its elevators and escalators in Russia while continuing all existing maintenance deals.
Pirelli, an Italian tyre manufacturer
Renault, a French automobile company
Timken, an American industrial company
Whirlpool, American manufacturer and marketer of home appliances


== See also ==
Corporate responses to the 2022 Russian invasion of Ukraine
List of companies that applied sanctions during the Russo-Ukrainian War
List of people and organizations sanctioned during the Russo-Ukrainian War
International sanctions during the 2022 Russian invasion of Ukraine
International Sponsors of War
Disinvestment from Israel
Disinvestment from South Africa
"Do not buy Russian goods!"
Boycott Russian Films


== References ==

In [86]:
TITLE = '=='
MIN_LENGTH = 5

paragraphs = data[example].split('\n')
paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]

print(f'{len(paragraphs_processed)} Paragraphs Extracted from {len(paragraphs)}\n{round(len(paragraphs_processed)/len(paragraphs)*100,1)}%')

74 Paragraphs Extracted from 168
44.0%

### Text Preprocessing: Paragraph Filtering

**Purpose:** To perform an initial cleaning of the raw text by filtering out structural elements and short, uninformative lines. This step aims to prepare cleaner text segments for downstream NER processing by removing elements such as section titles and empty or minimal lines.

**Date:** 2026-09-24

In [87]:
TITLE = '=='
MIN_LENGTH = 5

data_processed = {}

total_paragraphs = 0
total_processed = 0

for key, text in data.items():
  paragraphs = text.split('\n')
  paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]
  data_processed[key] = paragraphs_processed

  total_paragraphs += len(paragraphs)
  total_processed += len(paragraphs_processed)

print(f'{total_processed} paragraphs extracted from {total_paragraphs}\n {round(total_processed/total_paragraphs*100,1)}%')

42822 paragraphs extracted from 88029
 48.6%

In [88]:
example = np.random.choice([*data_processed],1)[0]

print(f'PAGE: {example}:\n\n{data_processed[example]}')

PAGE: Battle of Mala Tokmachka:

['In June 2023, a battle took place around the village of Mala Tokmachka as part of the 2023 Ukrainian counteroffensive and during the Russian invasion of Ukraine.', 'At the beginning of the Russian invasion of Ukraine in 2022, Mala Tokmachka quickly became a frontline settlement. The population would drop to only around 200 people by May 2023 due to the proximity of the fighting to the village and consistent Russian shelling which destroyed much of the local infrastructure and utilities. On 13 June 2023, French researcher Philippe Gros referred to the Ukrainian counteroffensive operations south of Mala Tokmachka as a "major axis", with the intention of advancing in the direction of the occupied city of Melitopol, which had been captured by Russian forces early into the invasion. David Axe of Forbes wrote that "perhaps 10,000 or more" Russian soldiers from the 70th, 291st, 429th, and 503rd Motor Rifle Regiments from the 58th Combined Arms Army\'s 42nd Guards Motor Rifle Division were stationed on the front lines near Tokmak. The 22nd and 45th Guards Spetsnaz Brigades were also reported by Axe to be in reserve.', 'On 7 June 2023, Ukrainian forces would first attempt to push the fighting away from the settlement while the Ukrainian 47th Mechanized Brigade and 33rd Mechanized Brigade would launch a mechanized assault on the village. Despite being armed with new western equipment, the initial attack went poorly. Russian scouts from the 70th and 291st motor rifle regiments spotted the Ukrainian armored column and called in Ka 52 attack helicopters. The Ukrainian tank column came under anti-tank missile and small arms fire while attempting to cross a minefield outside of the village. Trapped under fire and taking losses, the column retreated. Crews bailed out of their disabled vehicles and dragged dead and wounded with them out of the battlefield. Forbes reported that Ukrainian equipment loses were one IMR-2, a one Leopard 2A6 and as many as nine Bradleys with the some of their crews surviving. The ISW reported that the Russian Ministry of Defense responded to the Ukrainian attack with an uncharacteristic degree of coherency and praised the 42nd Guards Motor Rifle Division, 70th Guards Motor Rifle Regiment and 291st Motor Rifle Regiment for repelling the Ukrainian attack and regaining lost positions.', 'On 8 June, the 47th Mechanized Brigade attempted to use 6 Finnish donated Leopard 2R mine cleaning tanks, a German Wisent and an ex-Soviet BMR-2 to breach the Russian minefield but were forced to abandon 3 of the Leopard 2Rs and both the Wisent and the BMR-2 after one of the Leopard 2Rs struck a TM-62 anti tank mine and Russian helicopters and artillery hit the others vehicles. 50% of the 47th Brigade’s engineer battalion became casualties, however Forbes reported that the unit was still intact citing a video that the battalion posted after the engagement showing a Leopard 2R, two Soviet-style armored tractors fitted with UR-77 rocket-propelled mine clearing charges and a German Wisent.', 'On 9 June, Ukrainian forces launched a second mechanized assault capturing one height near the village. The assault group later came under artillery fire after being spotted by Russian drone operators and were forced to retreat.', "David Axe, a Forbes journalist, opined that the Ukrainian defeat near Mala Tokmachka was a military disaster, with both the 33rd and 47th losing 15% of their soldiers killed or wounded, and losing a fifth of Ukraine's M2 Bradleys, a fifth of its Leopard 2A6s and half its Leopard 2Rs with Russian forces in return only suffering light casualties. Photographic evidence showed that at least 4 Leopard 2A6 tanks, 3 Leopard 2R demining tanks, 17 Bradley infantry fighting vehicles, and 1 Wisent were destroyed. The battle was also the first documented loss of a Leopard 2 during the Russo-Ukrainian war. Some of the damaged vehicles were later recovered and repaired by Ukrainian forces. Ukrainian sources claimed that Russian forces were inflating Ukrainian equipment losses at Mala Tokmachka. Russian forces would later publish a video on 13 June showing 2 captured Leopard 2 tanks and multiple M2 Bradleys.", 'The defeat at Mala Tokmachka resulted in Ukrainian commanders switching to dismounted infantry attacks rather than mechanized assaults in order to not risk more armored vehicles. This would result in lowered armor losses but higher infantry casualties. On 30 June 2023, the Institute for the Study of War opined that the lack of a major breakthrough by Ukrainian forces around Mala Tokmachka would lead to less attacks and the beginning of positional fighting.', 'It was later reported that Russian forces quadrupled the depth of their defensive minefields, from 120 meters to 500 meters and also increased the density of mines within the expanded fields.', 'On 12 June, Russian military reporters said that Russian forces counterattacked Ukrainian positions south of Orikhiv. ', 'On 15 June, Ukrainian Brigadier-General Oleksii Hromov told a media briefing that Ukrainian forces had advanced by up to 3 km (1.8 miles) near Mala Tokmachka.', 'On 21 June, Ukrainian General Staff spokesperson Andriy Kovalev claimed that Ukrainian forces had made several gains around Mala Tokmachka.', 'On 28 June, Markus posted a video on Facebook about how he and soldiers under his command captured a Russian trench after 24 hours of assaults and were exhausted.', 'On 30 June 2023 headmaster Sergeant Major Valerii Markus of the 47th Mechanized Brigade met with President of Ukraine Volodymyr Zelenskyy and complained about the decisions of the unit\'s command regarding lack of interest in soldiers morale and officers incompetence during the battle. Markus was later voluntarily demoted to private after calling the brigade\'s commander, Lt. Col. Oleksandr Sak an "immoral degenerate". Sak would later be sacked on 16 September 2023 and replaced by Colonel Oleksandr Pavlii. A Ukrainian veteran of the 47th Mechanized Brigade who lost his leg during the battle named Mykola Melnyk, criticized the leadership of the battle but praised the American donated M2 Bradleys during an interview saying: "The Bradley withstood everything".']

In [89]:
SAVE_PATH = '/content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json'

with open(SAVE_PATH, 'w', encoding='utf-8') as f:
    json.dump(data_processed, f, ensure_ascii=False, indent=2)

print(f'Saved to: {SAVE_PATH}')

Saved to: /content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json

## Initial NER application

**Purpose:** To perform an initial NER application with base models and analyze the results

**Date:** 2026-09-24

### DistilBERT

In [90]:
MODEL_DistilBERT = "dslim/distilbert-NER"
MODEL_DistilBERT

ner_DistilBERT = pipeline("ner",
               model=MODEL_DistilBERT,
               aggregation_strategy='average')

ner_DistilBERT

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

TokenClassificationPipeline: {'model': 'DistilBertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [91]:
output_DistilBERT = ner_DistilBERT(data_processed[example])
output_DistilBERT

[[{'entity_group': 'LOC',
   'score': np.float32(0.9759275),
   'word': 'Mala Tokmachka',
   'start': 56,
   'end': 70},
  {'entity_group': 'MISC',
   'score': np.float32(0.9971994),
   'word': 'Ukrainian',
   'start': 91,
   'end': 100},
  {'entity_group': 'MISC',
   'score': np.float32(0.9982047),
   'word': 'Russian',
   'start': 133,
   'end': 140},
  {'entity_group': 'LOC',
   'score': np.float32(0.9971464),
   'word': 'Ukraine',
   'start': 153,
   'end': 160}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.998142),
   'word': 'Russian',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.9981012),
   'word': 'Ukraine',
   'start': 44,
   'end': 51},
  {'entity_group': 'LOC',
   'score': np.float32(0.9900874),
   'word': 'Mala Tokmachka',
   'start': 61,
   'end': 75},
  {'entity_group': 'MISC',
   'score': np.float32(0.99874085),
   'word': 'Russian',
   'start': 246,
   'end': 253},
  {'entity_group': 'MISC',
   'score': np.float32(0.9974718),
   'word': 'French',
   'start': 344,
   'end': 350},
  {'entity_group': 'PER',
   'score': np.float32(0.99857664),
   'word': 'Philippe Gros',
   'start': 362,
   'end': 375},
  {'entity_group': 'MISC',
   'score': np.float32(0.99861467),
   'word': 'Ukrainian',
   'start': 392,
   'end': 401},
  {'entity_group': 'LOC',
   'score': np.float32(0.93380356),
   'word': 'Mala Tokmachka',
   'start': 439,
   'end': 453},
  {'entity_group': 'LOC',
   'score': np.float32(0.9888018),
   'word': 'Melitopol',
   'start': 546,
   'end': 555},
  {'entity_group': 'MISC',
   'score': np.float32(0.9981614),
   'word': 'Russian',
   'start': 584,
   'end': 591},
  {'entity_group': 'PER',
   'score': np.float32(0.99874216),
   'word': 'David Axe',
   'start': 624,
   'end': 633},
  {'entity_group': 'ORG',
   'score': np.float32(0.46789053),
   'word': 'Forbes',
   'start': 637,
   'end': 643},
  {'entity_group': 'MISC',
   'score': np.float32(0.9983171),
   'word': 'Russian',
   'start': 680,
   'end': 687},
  {'entity_group': 'ORG',
   'score': np.float32(0.85308707),
   'word': 'Motor Rifle',
   'start': 736,
   'end': 747},
  {'entity_group': 'ORG',
   'score': np.float32(0.85432893),
   'word': 'Combined Arms Army',
   'start': 772,
   'end': 790},
  {'entity_group': 'ORG',
   'score': np.float32(0.8634458),
   'word': 'Guards Motor Rifle Division',
   'start': 798,
   'end': 825},
  {'entity_group': 'LOC',
   'score': np.float32(0.9959519),
   'word': 'Tokmak',
   'start': 865,
   'end': 871},
  {'entity_group': 'ORG',
   'score': np.float32(0.68436766),
   'word': 'Guards Spetsnaz Brigades',
   'start': 891,
   'end': 915},
  {'entity_group': 'ORG',
   'score': np.float32(0.96785986),
   'word': 'Axe',
   'start': 938,
   'end': 941}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99382883),
   'word': 'Ukrainian',
   'start': 16,
   'end': 25},
  {'entity_group': 'MISC',
   'score': np.float32(0.9897613),
   'word': 'Ukrainian',
   'start': 109,
   'end': 118},
  {'entity_group': 'ORG',
   'score': np.float32(0.8725436),
   'word': 'Mechanized Brigade',
   'start': 124,
   'end': 142},
  {'entity_group': 'ORG',
   'score': np.float32(0.8802926),
   'word': 'Mechanized Brigade',
   'start': 152,
   'end': 170},
  {'entity_group': 'MISC',
   'score': np.float32(0.9958675),
   'word': 'Russian',
   'start': 301,
   'end': 308},
  {'entity_group': 'MISC',
   'score': np.float32(0.99737084),
   'word': 'Ukrainian',
   'start': 374,
   'end': 383},
  {'entity_group': 'MISC',
   'score': np.float32(0.78384024),
   'word': 'Ka 52',
   'start': 413,
   'end': 418},
  {'entity_group': 'MISC',
   'score': np.float32(0.9981384),
   'word': 'Ukrainian',
   'start': 443,
   'end': 452},
  {'entity_group': 'ORG',
   'score': np.float32(0.7645063),
   'word': 'Forbes',
   'start': 743,
   'end': 749},
  {'entity_group': 'MISC',
   'score': np.float32(0.9980868),
   'word': 'Ukrainian',
   'start': 764,
   'end': 773},
  {'entity_group': 'MISC',
   'score': np.float32(0.9712204),
   'word': 'IMR',
   'start': 799,
   'end': 802},
  {'entity_group': 'MISC',
   'score': np.float32(0.96991944),
   'word': '-',
   'start': 802,
   'end': 803},
  {'entity_group': 'MISC',
   'score': np.float32(0.92766035),
   'word': '2',
   'start': 803,
   'end': 804},
  {'entity_group': 'MISC',
   'score': np.float32(0.951326),
   'word': 'Leopard',
   'start': 812,
   'end': 819},
  {'entity_group': 'MISC',
   'score': np.float32(0.6008583),
   'word': '2A6',
   'start': 820,
   'end': 823},
  {'entity_group': 'MISC',
   'score': np.float32(0.9110303),
   'word': 'Bradleys',
   'start': 844,
   'end': 852},
  {'entity_group': 'ORG',
   'score': np.float32(0.9947212),
   'word': 'ISW',
   'start': 897,
   'end': 900},
  {'entity_group': 'MISC',
   'score': np.float32(0.9692405),
   'word': 'Russian',
   'start': 919,
   'end': 926},
  {'entity_group': 'ORG',
   'score': np.float32(0.98580456),
   'word': 'Ministry of Defense',
   'start': 927,
   'end': 946},
  {'entity_group': 'MISC',
   'score': np.float32(0.99452305),
   'word': 'Ukrainian',
   'start': 964,
   'end': 973},
  {'entity_group': 'ORG',
   'score': np.float32(0.9442473),
   'word': 'Guards Motor Rifle Division',
   'start': 1047,
   'end': 1074},
  {'entity_group': 'ORG',
   'score': np.float32(0.91526306),
   'word': 'Guards Motor Rifle Regiment',
   'start': 1081,
   'end': 1108},
  {'entity_group': 'ORG',
   'score': np.float32(0.90831643),
   'word': 'Motor Rifle Regiment',
   'start': 1119,
   'end': 1139},
  {'entity_group': 'MISC',
   'score': np.float32(0.9961887),
   'word': 'Ukrainian',
   'start': 1158,
   'end': 1167}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.72450376),
   'word': 'Mechanized Brigade',
   'start': 20,
   'end': 38},
  {'entity_group': 'MISC',
   'score': np.float32(0.9971374),
   'word': 'Finnish',
   'start': 58,
   'end': 65},
  {'entity_group': 'MISC',
   'score': np.float32(0.78535485),
   'word': 'Leopard 2R',
   'start': 74,
   'end': 84},
  {'entity_group': 'MISC',
   'score': np.float32(0.92776585),
   'word': 'German Wisent',
   'start': 108,
   'end': 121},
  {'entity_group': 'MISC',
   'score': np.float32(0.9707664),
   'word': '-',
   'start': 131,
   'end': 132},
  {'entity_group': 'MISC',
   'score': np.float32(0.99689543),
   'word': 'Soviet',
   'start': 132,
   'end': 138},
  {'entity_group': 'MISC',
   'score': np.float32(0.87217534),
   'word': 'BMR',
   'start': 139,
   'end': 142},
  {'entity_group': 'MISC',
   'score': np.float32(0.88412535),
   'word': '-',
   'start': 142,
   'end': 143},
  {'entity_group': 'MISC',
   'score': np.float32(0.74188954),
   'word': '2',
   'start': 143,
   'end': 144},
  {'entity_group': 'MISC',
   'score': np.float32(0.99734676),
   'word': 'Russian',
   'start': 159,
   'end': 166},
  {'entity_group': 'MISC',
   'score': np.float32(0.8599256),
   'word': 'Leopard',
   'start': 213,
   'end': 220},
  {'entity_group': 'MISC',
   'score': np.float32(0.5138523),
   'word': '2Rs',
   'start': 221,
   'end': 224},
  {'entity_group': 'MISC',
   'score': np.float32(0.6051188),
   'word': 'Wisent',
   'start': 238,
   'end': 244},
  {'entity_group': 'MISC',
   'score': np.float32(0.67307967),
   'word': 'BMR',
   'start': 253,
   'end': 256},
  {'entity_group': 'MISC',
   'score': np.float32(0.83729464),
   'word': '-',
   'start': 256,
   'end': 257},
  {'entity_group': 'MISC',
   'score': np.float32(0.85398096),
   'word': '2',
   'start': 257,
   'end': 258},
  {'entity_group': 'MISC',
   'score': np.float32(0.83056056),
   'word': 'Leopard',
   'start': 276,
   'end': 283},
  {'entity_group': 'MISC',
   'score': np.float32(0.98439336),
   'word': 'TM',
   'start': 297,
   'end': 299},
  {'entity_group': 'MISC',
   'score': np.float32(0.98535883),
   'word': '-',
   'start': 299,
   'end': 300},
  {'entity_group': 'MISC',
   'score': np.float32(0.97686213),
   'word': '62',
   'start': 300,
   'end': 302},
  {'entity_group': 'MISC',
   'score': np.float32(0.9978642),
   'word': 'Russian',
   'start': 322,
   'end': 329},
  {'entity_group': 'ORG',
   'score': np.float32(0.5250263),
   'word': 'Brigade',
   'start': 397,
   'end': 404},
  {'entity_group': 'ORG',
   'score': np.float32(0.97499734),
   'word': 'Forbes',
   'start': 453,
   'end': 459},
  {'entity_group': 'MISC',
   'score': np.float32(0.70654273),
   'word': 'Leopard 2R',
   'start': 572,
   'end': 582},
  {'entity_group': 'MISC',
   'score': np.float32(0.9962309),
   'word': 'Soviet',
   'start': 588,
   'end': 594},
  {'entity_group': 'MISC',
   'score': np.float32(0.98593813),
   'word': '-',
   'start': 594,
   'end': 595},
  {'entity_group': 'MISC',
   'score': np.float32(0.9657105),
   'word': 'style',
   'start': 595,
   'end': 600},
  {'entity_group': 'MISC',
   'score': np.float32(0.9858991),
   'word': 'UR',
   'start': 630,
   'end': 632},
  {'entity_group': 'MISC',
   'score': np.float32(0.9848214),
   'word': '-',
   'start': 632,
   'end': 633},
  {'entity_group': 'MISC',
   'score': np.float32(0.98328096),
   'word': '77',
   'start': 633,
   'end': 635},
  {'entity_group': 'MISC',
   'score': np.float32(0.90454197),
   'word': 'German Wisent',
   'start': 681,
   'end': 694}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9971066),
   'word': 'Ukrainian',
   'start': 11,
   'end': 20},
  {'entity_group': 'MISC',
   'score': np.float32(0.9976839),
   'word': 'Russian',
   'start': 177,
   'end': 184}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9990591),
   'word': 'David Axe',
   'start': 0,
   'end': 9},
  {'entity_group': 'ORG',
   'score': np.float32(0.9860205),
   'word': 'Forbes',
   'start': 13,
   'end': 19},
  {'entity_group': 'MISC',
   'score': np.float32(0.99833715),
   'word': 'Ukrainian',
   'start': 48,
   'end': 57},
  {'entity_group': 'LOC',
   'score': np.float32(0.990099),
   'word': 'Mala Tokmachka',
   'start': 70,
   'end': 84},
  {'entity_group': 'LOC',
   'score': np.float32(0.9990693),
   'word': 'Ukraine',
   'start': 208,
   'end': 215},
  {'entity_group': 'MISC',
   'score': np.float32(0.8830267),
   'word': 'M2 Bradleys',
   'start': 218,
   'end': 229},
  {'entity_group': 'MISC',
   'score': np.float32(0.59267974),
   'word': 'Leopard 2A6s',
   'start': 246,
   'end': 258},
  {'entity_group': 'MISC',
   'score': np.float32(0.84233356),
   'word': 'Leopard',
   'start': 272,
   'end': 279},
  {'entity_group': 'MISC',
   'score': np.float32(0.44341365),
   'word': '2Rs',
   'start': 280,
   'end': 283},
  {'entity_group': 'MISC',
   'score': np.float32(0.9984301),
   'word': 'Russian',
   'start': 289,
   'end': 296},
  {'entity_group': 'MISC',
   'score': np.float32(0.6996335),
   'word': 'Leopard 2A6',
   'start': 392,
   'end': 403},
  {'entity_group': 'MISC',
   'score': np.float32(0.66772044),
   'word': 'Leopard 2R',
   'start': 413,
   'end': 423},
  {'entity_group': 'MISC',
   'score': np.float32(0.8226969),
   'word': 'Bradley',
   'start': 443,
   'end': 450},
  {'entity_group': 'MISC',
   'score': np.float32(0.74124825),
   'word': 'Wisent',
   'start': 485,
   'end': 491},
  {'entity_group': 'MISC',
   'score': np.float32(0.7766057),
   'word': 'Leopard 2',
   'start': 559,
   'end': 568},
  {'entity_group': 'MISC',
   'score': np.float32(0.9973532),
   'word': 'Russo',
   'start': 580,
   'end': 585},
  {'entity_group': 'MISC',
   'score': np.float32(0.9957973),
   'word': '-',
   'start': 585,
   'end': 586},
  {'entity_group': 'MISC',
   'score': np.float32(0.9955509),
   'word': 'Ukrainian',
   'start': 586,
   'end': 595},
  {'entity_group': 'MISC',
   'score': np.float32(0.99712306),
   'word': 'Ukrainian',
   'start': 667,
   'end': 676},
  {'entity_group': 'MISC',
   'score': np.float32(0.9965927),
   'word': 'Ukrainian',
   'start': 685,
   'end': 694},
  {'entity_group': 'MISC',
   'score': np.float32(0.99827075),
   'word': 'Russian',
   'start': 716,
   'end': 723},
  {'entity_group': 'MISC',
   'score': np.float32(0.9971999),
   'word': 'Ukrainian',
   'start': 746,
   'end': 755},
  {'entity_group': 'LOC',
   'score': np.float32(0.98023957),
   'word': 'Mala Tokmachka',
   'start': 776,
   'end': 790},
  {'entity_group': 'MISC',
   'score': np.float32(0.9980679),
   'word': 'Russian',
   'start': 792,
   'end': 799},
  {'entity_group': 'MISC',
   'score': np.float32(0.77524257),
   'word': 'Leopard 2',
   'start': 865,
   'end': 874},
  {'entity_group': 'MISC',
   'score': np.float32(0.835801),
   'word': 'M2 Bradleys',
   'start': 894,
   'end': 905}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99020034),
   'word': 'Mala Tokmachka',
   'start': 14,
   'end': 28},
  {'entity_group': 'MISC',
   'score': np.float32(0.9969465),
   'word': 'Ukrainian',
   'start': 41,
   'end': 50},
  {'entity_group': 'ORG',
   'score': np.float32(0.97964555),
   'word': 'Institute for the Study of War',
   'start': 274,
   'end': 304},
  {'entity_group': 'MISC',
   'score': np.float32(0.99787176),
   'word': 'Ukrainian',
   'start': 353,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.9727828),
   'word': 'Mala Tokmachka',
   'start': 377,
   'end': 391}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9983992),
   'word': 'Russian',
   'start': 27,
   'end': 34}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9980781),
   'word': 'Russian',
   'start': 12,
   'end': 19},
  {'entity_group': 'MISC',
   'score': np.float32(0.9980046),
   'word': 'Russian',
   'start': 49,
   'end': 56},
  {'entity_group': 'MISC',
   'score': np.float32(0.9975249),
   'word': 'Ukrainian',
   'start': 80,
   'end': 89},
  {'entity_group': 'LOC',
   'score': np.float32(0.99780846),
   'word': 'Orikhiv',
   'start': 109,
   'end': 116}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9977925),
   'word': 'Ukrainian',
   'start': 12,
   'end': 21},
  {'entity_group': 'PER',
   'score': np.float32(0.99875283),
   'word': 'Oleksii Hromov',
   'start': 40,
   'end': 54},
  {'entity_group': 'MISC',
   'score': np.float32(0.99787724),
   'word': 'Ukrainian',
   'start': 82,
   'end': 91},
  {'entity_group': 'LOC',
   'score': np.float32(0.9777343),
   'word': 'Mala Tokmachka',
   'start': 143,
   'end': 157}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.997621),
   'word': 'Ukrainian',
   'start': 12,
   'end': 21},
  {'entity_group': 'PER',
   'score': np.float32(0.99895597),
   'word': 'Andriy Kovalev',
   'start': 49,
   'end': 63},
  {'entity_group': 'MISC',
   'score': np.float32(0.997883),
   'word': 'Ukrainian',
   'start': 77,
   'end': 86},
  {'entity_group': 'LOC',
   'score': np.float32(0.98516136),
   'word': 'Mala Tokmachka',
   'start': 124,
   'end': 138}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9970018),
   'word': 'Markus',
   'start': 12,
   'end': 18},
  {'entity_group': 'MISC',
   'score': np.float32(0.998295),
   'word': 'Russian',
   'start': 101,
   'end': 108}],
 [{'entity_group': 'PER',
   'score': np.float32(0.99688625),
   'word': 'Valerii Markus',
   'start': 42,
   'end': 56},
  {'entity_group': 'ORG',
   'score': np.float32(0.5889441),
   'word': 'Mechanized Brigade',
   'start': 69,
   'end': 87},
  {'entity_group': 'LOC',
   'score': np.float32(0.93935347),
   'word': 'Ukraine',
   'start': 110,
   'end': 117},
  {'entity_group': 'PER',
   'score': np.float32(0.99749243),
   'word': 'Volodymyr Zelenskyy',
   'start': 118,
   'end': 137},
  {'entity_group': 'PER',
   'score': np.float32(0.9973252),
   'word': 'Markus',
   'start': 286,
   'end': 292},
  {'entity_group': 'PER',
   'score': np.float32(0.9955292),
   'word': 'Oleksandr Sak',
   'start': 382,
   'end': 395},
  {'entity_group': 'PER',
   'score': np.float32(0.99788153),
   'word': 'Sak',
   'start': 421,
   'end': 424},
  {'entity_group': 'PER',
   'score': np.float32(0.9985075),
   'word': 'Oleksandr Pavlii',
   'start': 492,
   'end': 508},
  {'entity_group': 'MISC',
   'score': np.float32(0.9972498),
   'word': 'Ukrainian',
   'start': 512,
   'end': 521},
  {'entity_group': 'ORG',
   'score': np.float32(0.66301703),
   'word': 'Mechanized Brigade',
   'start': 542,
   'end': 560},
  {'entity_group': 'PER',
   'score': np.float32(0.99867415),
   'word': 'Mykola Melnyk',
   'start': 602,
   'end': 615},
  {'entity_group': 'MISC',
   'score': np.float32(0.991855),
   'word': 'American',
   'start': 673,
   'end': 681},
  {'entity_group': 'MISC',
   'score': np.float32(0.7541244),
   'word': 'M2 Bradleys',
   'start': 690,
   'end': 701},
  {'entity_group': 'MISC',
   'score': np.float32(0.37911192),
   'word': 'Bradley',
   'start': 735,
   'end': 742}]]

In [92]:
df_DistilBERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_DistilBERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",LOC,0.975927,Mala Tokmachka,56,70
1,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",MISC,0.997199,Ukrainian,91,100
2,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",MISC,0.998205,Russian,133,140
3,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",LOC,0.997146,Ukraine,153,160
4,Battle of Mala Tokmachka,1,At the beginning of the Russian invasion of Uk...,MISC,0.998142,Russian,24,31
...,...,...,...,...,...,...,...,...
135,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,ORG,0.663017,Mechanized Brigade,542,560
136,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,PER,0.998674,Mykola Melnyk,602,615
137,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.991855,American,673,681
138,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.754124,M2 Bradleys,690,701
139,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.379112,Bradley,735,742

### BERT

In [93]:
MODEL_BERT = "dslim/bert-base-NER"
MODEL_BERT

ner_BERT = pipeline("ner",
               model=MODEL_BERT,
               aggregation_strategy='average')

ner_BERT

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

TokenClassificationPipeline: {'model': 'BertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [94]:
output_BERT = ner_BERT(data_processed[example])
output_BERT

[[{'entity_group': 'LOC',
   'score': np.float32(0.7361562),
   'word': 'Mala Tokmachka',
   'start': 56,
   'end': 70},
  {'entity_group': 'MISC',
   'score': np.float32(0.9995716),
   'word': 'Ukrainian',
   'start': 91,
   'end': 100},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997085),
   'word': 'Russian',
   'start': 133,
   'end': 140},
  {'entity_group': 'LOC',
   'score': np.float32(0.99975055),
   'word': 'Ukraine',
   'start': 153,
   'end': 160}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997297),
   'word': 'Russian',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997954),
   'word': 'Ukraine',
   'start': 44,
   'end': 51},
  {'entity_group': 'LOC',
   'score': np.float32(0.744784),
   'word': 'Mala Tokmachka',
   'start': 61,
   'end': 75},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997429),
   'word': 'Russian',
   'start': 246,
   'end': 253},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997155),
   'word': 'French',
   'start': 344,
   'end': 350},
  {'entity_group': 'PER',
   'score': np.float32(0.9988056),
   'word': 'Philippe Gros',
   'start': 362,
   'end': 375},
  {'entity_group': 'MISC',
   'score': np.float32(0.99975103),
   'word': 'Ukrainian',
   'start': 392,
   'end': 401},
  {'entity_group': 'LOC',
   'score': np.float32(0.74635565),
   'word': 'Mala Tokmachka',
   'start': 439,
   'end': 453},
  {'entity_group': 'LOC',
   'score': np.float32(0.6623307),
   'word': 'Melitopol',
   'start': 546,
   'end': 555},
  {'entity_group': 'MISC',
   'score': np.float32(0.99977213),
   'word': 'Russian',
   'start': 584,
   'end': 591},
  {'entity_group': 'PER',
   'score': np.float32(0.9231081),
   'word': 'David Axe',
   'start': 624,
   'end': 633},
  {'entity_group': 'ORG',
   'score': np.float32(0.92383504),
   'word': 'Forbes',
   'start': 637,
   'end': 643},
  {'entity_group': 'MISC',
   'score': np.float32(0.99975866),
   'word': 'Russian',
   'start': 680,
   'end': 687},
  {'entity_group': 'ORG',
   'score': np.float32(0.5481965),
   'word': '58th',
   'start': 767,
   'end': 771},
  {'entity_group': 'ORG',
   'score': np.float32(0.8841967),
   'word': 'Combined Arms Army',
   'start': 772,
   'end': 790},
  {'entity_group': 'ORG',
   'score': np.float32(0.9888035),
   'word': '42nd Guards Motor Rifle Division',
   'start': 793,
   'end': 825},
  {'entity_group': 'LOC',
   'score': np.float32(0.55099326),
   'word': 'Tokmak',
   'start': 865,
   'end': 871},
  {'entity_group': 'ORG',
   'score': np.float32(0.82107896),
   'word': '45th Guards Spetsnaz',
   'start': 886,
   'end': 906},
  {'entity_group': 'PER',
   'score': np.float32(0.6552702),
   'word': 'Axe',
   'start': 938,
   'end': 941}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997297),
   'word': 'Ukrainian',
   'start': 16,
   'end': 25},
  {'entity_group': 'MISC',
   'score': np.float32(0.99953735),
   'word': 'Ukrainian',
   'start': 109,
   'end': 118},
  {'entity_group': 'ORG',
   'score': np.float32(0.8400095),
   'word': '47th Mechanized Brigade',
   'start': 119,
   'end': 142},
  {'entity_group': 'ORG',
   'score': np.float32(0.99659497),
   'word': '33rd Mechanized Brigade',
   'start': 147,
   'end': 170},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997665),
   'word': 'Russian',
   'start': 301,
   'end': 308},
  {'entity_group': 'MISC',
   'score': np.float32(0.99971837),
   'word': 'Ukrainian',
   'start': 374,
   'end': 383},
  {'entity_group': 'MISC',
   'score': np.float32(0.986611),
   'word': 'Ka',
   'start': 413,
   'end': 415},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997348),
   'word': 'Ukrainian',
   'start': 443,
   'end': 452},
  {'entity_group': 'PER',
   'score': np.float32(0.97153014),
   'word': 'Forbes',
   'start': 743,
   'end': 749},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997725),
   'word': 'Ukrainian',
   'start': 764,
   'end': 773},
  {'entity_group': 'MISC',
   'score': np.float32(0.5014549),
   'word': 'IMR',
   'start': 799,
   'end': 802},
  {'entity_group': 'MISC',
   'score': np.float32(0.9894164),
   'word': '2',
   'start': 803,
   'end': 804},
  {'entity_group': 'MISC',
   'score': np.float32(0.67922723),
   'word': 'Leopard 2A6',
   'start': 812,
   'end': 823},
  {'entity_group': 'ORG',
   'score': np.float32(0.49960664),
   'word': 'ISW',
   'start': 897,
   'end': 900},
  {'entity_group': 'MISC',
   'score': np.float32(0.9987343),
   'word': 'Russian',
   'start': 919,
   'end': 926},
  {'entity_group': 'ORG',
   'score': np.float32(0.94497186),
   'word': 'Ministry of Defense',
   'start': 927,
   'end': 946},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997032),
   'word': 'Ukrainian',
   'start': 964,
   'end': 973},
  {'entity_group': 'ORG',
   'score': np.float32(0.99115306),
   'word': '42nd Guards Motor Rifle Division',
   'start': 1042,
   'end': 1074},
  {'entity_group': 'ORG',
   'score': np.float32(0.89222574),
   'word': '70th Guards Motor Rifle Regiment',
   'start': 1076,
   'end': 1108},
  {'entity_group': 'ORG',
   'score': np.float32(0.9167776),
   'word': 'Motor Rifle Regiment',
   'start': 1119,
   'end': 1139},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997416),
   'word': 'Ukrainian',
   'start': 1158,
   'end': 1167}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.8314803),
   'word': '47th Mechanized Brigade',
   'start': 15,
   'end': 38},
  {'entity_group': 'MISC',
   'score': np.float32(0.99971455),
   'word': 'Finnish',
   'start': 58,
   'end': 65},
  {'entity_group': 'MISC',
   'score': np.float32(0.63422596),
   'word': 'Leopard 2R',
   'start': 74,
   'end': 84},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996389),
   'word': 'German',
   'start': 108,
   'end': 114},
  {'entity_group': 'MISC',
   'score': np.float32(0.99517375),
   'word': 'ex',
   'start': 129,
   'end': 131},
  {'entity_group': 'MISC',
   'score': np.float32(0.99867475),
   'word': 'Soviet',
   'start': 132,
   'end': 138},
  {'entity_group': 'MISC',
   'score': np.float32(0.49972475),
   'word': 'BMR',
   'start': 139,
   'end': 142},
  {'entity_group': 'MISC',
   'score': np.float32(0.9623304),
   'word': '2',
   'start': 143,
   'end': 144},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997948),
   'word': 'Russian',
   'start': 159,
   'end': 166},
  {'entity_group': 'MISC',
   'score': np.float32(0.77099407),
   'word': 'Leopard 2Rs',
   'start': 213,
   'end': 224},
  {'entity_group': 'MISC',
   'score': np.float32(0.64227694),
   'word': 'BMR - 2',
   'start': 253,
   'end': 258},
  {'entity_group': 'MISC',
   'score': np.float32(0.77075624),
   'word': 'Leopard 2Rs',
   'start': 276,
   'end': 287},
  {'entity_group': 'MISC',
   'score': np.float32(0.50506115),
   'word': 'TM',
   'start': 297,
   'end': 299},
  {'entity_group': 'MISC',
   'score': np.float32(0.9797062),
   'word': '62',
   'start': 300,
   'end': 302},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997756),
   'word': 'Russian',
   'start': 322,
   'end': 329},
  {'entity_group': 'ORG',
   'score': np.float32(0.7486024),
   'word': '47th Brigade',
   'start': 392,
   'end': 404},
  {'entity_group': 'PER',
   'score': np.float32(0.99179626),
   'word': 'Forbes',
   'start': 453,
   'end': 459},
  {'entity_group': 'MISC',
   'score': np.float32(0.71937585),
   'word': 'Leopard 2R',
   'start': 572,
   'end': 582},
  {'entity_group': 'MISC',
   'score': np.float32(0.9990108),
   'word': 'Soviet',
   'start': 588,
   'end': 594},
  {'entity_group': 'MISC',
   'score': np.float32(0.5019393),
   'word': 'UR',
   'start': 630,
   'end': 632},
  {'entity_group': 'MISC',
   'score': np.float32(0.7509128),
   'word': '77',
   'start': 633,
   'end': 635},
  {'entity_group': 'MISC',
   'score': np.float32(0.9995153),
   'word': 'German',
   'start': 681,
   'end': 687}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997173),
   'word': 'Ukrainian',
   'start': 11,
   'end': 20},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997743),
   'word': 'Russian',
   'start': 177,
   'end': 184}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9996996),
   'word': 'David Axe',
   'start': 0,
   'end': 9},
  {'entity_group': 'ORG',
   'score': np.float32(0.9919369),
   'word': 'Forbes',
   'start': 13,
   'end': 19},
  {'entity_group': 'MISC',
   'score': np.float32(0.99977475),
   'word': 'Ukrainian',
   'start': 48,
   'end': 57},
  {'entity_group': 'LOC',
   'score': np.float32(0.74694324),
   'word': 'Mala Tokmachka',
   'start': 70,
   'end': 84},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997203),
   'word': 'Ukraine',
   'start': 208,
   'end': 215},
  {'entity_group': 'MISC',
   'score': np.float32(0.5089494),
   'word': 'Leopard',
   'start': 246,
   'end': 253},
  {'entity_group': 'MISC',
   'score': np.float32(0.5456626),
   'word': 'Leopard',
   'start': 272,
   'end': 279},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997905),
   'word': 'Russian',
   'start': 289,
   'end': 296},
  {'entity_group': 'MISC',
   'score': np.float32(0.5415704),
   'word': 'Leopard 2A6',
   'start': 392,
   'end': 403},
  {'entity_group': 'MISC',
   'score': np.float32(0.7646991),
   'word': 'Leopard 2R',
   'start': 413,
   'end': 423},
  {'entity_group': 'MISC',
   'score': np.float32(0.97544247),
   'word': 'Bradley',
   'start': 443,
   'end': 450},
  {'entity_group': 'MISC',
   'score': np.float32(0.7836945),
   'word': 'Leopard 2',
   'start': 559,
   'end': 568},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997074),
   'word': 'Russo',
   'start': 580,
   'end': 585},
  {'entity_group': 'MISC',
   'score': np.float32(0.9845285),
   'word': 'Ukrainian',
   'start': 586,
   'end': 595},
  {'entity_group': 'MISC',
   'score': np.float32(0.99975234),
   'word': 'Ukrainian',
   'start': 667,
   'end': 676},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997478),
   'word': 'Ukrainian',
   'start': 685,
   'end': 694},
  {'entity_group': 'MISC',
   'score': np.float32(0.99978393),
   'word': 'Russian',
   'start': 716,
   'end': 723},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997656),
   'word': 'Ukrainian',
   'start': 746,
   'end': 755},
  {'entity_group': 'LOC',
   'score': np.float32(0.74630946),
   'word': 'Mala Tokmachka',
   'start': 776,
   'end': 790},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997795),
   'word': 'Russian',
   'start': 792,
   'end': 799},
  {'entity_group': 'MISC',
   'score': np.float32(0.7513991),
   'word': 'Leopard 2',
   'start': 865,
   'end': 874}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.7429259),
   'word': 'Mala Tokmachka',
   'start': 14,
   'end': 28},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997222),
   'word': 'Ukrainian',
   'start': 41,
   'end': 50},
  {'entity_group': 'ORG',
   'score': np.float32(0.99892277),
   'word': 'Institute for the Study of War',
   'start': 274,
   'end': 304},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997379),
   'word': 'Ukrainian',
   'start': 353,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.74670976),
   'word': 'Mala Tokmachka',
   'start': 377,
   'end': 391}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997738),
   'word': 'Russian',
   'start': 27,
   'end': 34}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99978083),
   'word': 'Russian',
   'start': 12,
   'end': 19},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997818),
   'word': 'Russian',
   'start': 49,
   'end': 56},
  {'entity_group': 'MISC',
   'score': np.float32(0.99969375),
   'word': 'Ukrainian',
   'start': 80,
   'end': 89},
  {'entity_group': 'LOC',
   'score': np.float32(0.738142),
   'word': 'Orikhiv',
   'start': 109,
   'end': 116}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99968445),
   'word': 'Ukrainian',
   'start': 12,
   'end': 21},
  {'entity_group': 'PER',
   'score': np.float32(0.7754072),
   'word': 'Oleksii Hromov',
   'start': 40,
   'end': 54},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997373),
   'word': 'Ukrainian',
   'start': 82,
   'end': 91},
  {'entity_group': 'LOC',
   'score': np.float32(0.7359309),
   'word': 'Mala Tokmachka',
   'start': 143,
   'end': 157}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.98826504),
   'word': 'Ukrainian',
   'start': 12,
   'end': 21},
  {'entity_group': 'ORG',
   'score': np.float32(0.9148947),
   'word': 'Staff',
   'start': 30,
   'end': 35},
  {'entity_group': 'PER',
   'score': np.float32(0.9022546),
   'word': 'Andriy Kovalev',
   'start': 49,
   'end': 63},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997391),
   'word': 'Ukrainian',
   'start': 77,
   'end': 86},
  {'entity_group': 'LOC',
   'score': np.float32(0.72569406),
   'word': 'Mala Tokmachka',
   'start': 124,
   'end': 138}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9996124),
   'word': 'Markus',
   'start': 12,
   'end': 18},
  {'entity_group': 'ORG',
   'score': np.float32(0.4793005),
   'word': 'Facebook',
   'start': 37,
   'end': 45},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997613),
   'word': 'Russian',
   'start': 101,
   'end': 108}],
 [{'entity_group': 'PER',
   'score': np.float32(0.8447527),
   'word': 'Valerii Markus',
   'start': 42,
   'end': 56},
  {'entity_group': 'ORG',
   'score': np.float32(0.8320718),
   'word': '47th Mechanized Brigade',
   'start': 64,
   'end': 87},
  {'entity_group': 'LOC',
   'score': np.float32(0.99961746),
   'word': 'Ukraine',
   'start': 110,
   'end': 117},
  {'entity_group': 'PER',
   'score': np.float32(0.80003023),
   'word': 'Volodymyr Zelenskyy',
   'start': 118,
   'end': 137},
  {'entity_group': 'PER',
   'score': np.float32(0.9988953),
   'word': 'Markus',
   'start': 286,
   'end': 292},
  {'entity_group': 'PER',
   'score': np.float32(0.95464504),
   'word': 'Oleksandr Sak',
   'start': 382,
   'end': 395},
  {'entity_group': 'PER',
   'score': np.float32(0.5462847),
   'word': 'Sak',
   'start': 421,
   'end': 424},
  {'entity_group': 'PER',
   'score': np.float32(0.8495741),
   'word': 'Oleksandr Pavlii',
   'start': 492,
   'end': 508},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996748),
   'word': 'Ukrainian',
   'start': 512,
   'end': 521},
  {'entity_group': 'ORG',
   'score': np.float32(0.83163786),
   'word': '47th Mechanized Brigade',
   'start': 537,
   'end': 560},
  {'entity_group': 'PER',
   'score': np.float32(0.9823254),
   'word': 'Mykola Melnyk',
   'start': 602,
   'end': 615},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997763),
   'word': 'American',
   'start': 673,
   'end': 681},
  {'entity_group': 'MISC',
   'score': np.float32(0.8926886),
   'word': 'Bradley',
   'start': 735,
   'end': 742}]]

In [95]:
df_BERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_BERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",LOC,0.975927,Mala Tokmachka,56,70
1,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",MISC,0.997199,Ukrainian,91,100
2,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",MISC,0.998205,Russian,133,140
3,Battle of Mala Tokmachka,0,"In June 2023, a battle took place around the v...",LOC,0.997146,Ukraine,153,160
4,Battle of Mala Tokmachka,1,At the beginning of the Russian invasion of Uk...,MISC,0.998142,Russian,24,31
...,...,...,...,...,...,...,...,...
135,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,ORG,0.663017,Mechanized Brigade,542,560
136,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,PER,0.998674,Mykola Melnyk,602,615
137,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.991855,American,673,681
138,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.754124,M2 Bradleys,690,701
139,Battle of Mala Tokmachka,12,On 30 June 2023 headmaster Sergeant Major Vale...,MISC,0.379112,Bradley,735,742

## Commit to repo

In [98]:
REPO_PATH = "/content/Corpus2GeoRAG"
GITHUB_USER = "idoschw3"
GITHUB_REPO = "Corpus2GeoRAG"
GITHUB_EMAIL = "193781032+idoschw3@users.noreply.github.com"
COMMIT_MESSAGE = "Update NER workflow"

os.chdir(REPO_PATH)

# Git identity
subprocess.run(["git", "config", "user.name", GITHUB_USER], check=True)
subprocess.run(["git", "config", "user.email", GITHUB_EMAIL], check=True)

# Make sure origin points to my fork
subprocess.run([
    "git", "remote", "set-url", "origin",
    f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}.git"
], check=True)

# Read GitHub token from Colab Secrets
github_token = userdata.get("GITHUB_TOKEN")

# Temporary authentication helper
askpass_path = "/tmp/github_askpass.sh"

with open(askpass_path, "w") as f:
    f.write(
        '#!/bin/sh\n'
        'case "$1" in\n'
        '  *Username*) echo "$GITHUB_USER" ;;\n'
        '  *Password*) echo "$GITHUB_TOKEN" ;;\n'
        'esac\n'
    )

os.chmod(askpass_path, 0o700)

env = os.environ.copy()
env["GITHUB_USER"] = GITHUB_USER
env["GITHUB_TOKEN"] = github_token
env["GIT_ASKPASS"] = askpass_path
env["GIT_TERMINAL_PROMPT"] = "0"

try:
    # Stage ALL repository changes
    subprocess.run(["git", "add", "-A"], check=True)

    # Commit only if there are changes
    status = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True,
        text=True,
        check=True
    )

    if status.stdout.strip():
        subprocess.run(
            ["git", "commit", "-m", COMMIT_MESSAGE],
            check=True
        )
        print("Changes committed.")
    else:
        print("No new changes to commit.")

    # Get current branch
    branch = subprocess.run(
        ["git", "branch", "--show-current"],
        capture_output=True,
        text=True,
        check=True
    ).stdout.strip()

    # Bring in changes already made directly on GitHub
    subprocess.run(
        ["git", "pull", "--rebase", "origin", branch],
        env=env,
        check=True
    )

    print("Local repository synchronized with GitHub.")

    # Push everything back to my fork
    subprocess.run(
        ["git", "push", "origin", branch],
        env=env,
        check=True
    )

    print(f"Successfully pushed to {GITHUB_USER}/{GITHUB_REPO} on branch '{branch}'.")

finally:
    if os.path.exists(askpass_path):
        os.remove(askpass_path)

No new changes to commit.
Local repository synchronized with GitHub.
Successfully pushed to idoschw3/Corpus2GeoRAG on branch 'main'.