<a href="https://colab.research.google.com/github/idoschw3/Corpus2GeoRAG/blob/main/ApplyNER/NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
from transformers import pipeline
from google.colab import userdata
import pandas as pd
import numpy as np
import subprocess
import json
import os

### Clone Corpus2GeoRAG Repository

In [62]:
%%bash
rm -rf Corpus2GeoRAG
git clone https://github.com/EtzionR/Corpus2GeoRAG.git

Cloning into 'Corpus2GeoRAG'...

### Data Loading and Initial Inspection

**Purpose:** To load the raw text data, which is crucial for subsequent NER tasks, from a JSON file. This section also includes an example to visually inspect the structure and content of a single entry, ensuring the data is correctly loaded and accessible.


**Input/Output:** Input is `/content/Corpus2GeoRAG/examples/DATA.json`.

**Date:** 2026-09-23

In [63]:
PATH = r'/content/Corpus2GeoRAG/examples/DATA.json'
PATH

'/content/Corpus2GeoRAG/examples/DATA.json'

In [64]:
with open(PATH, 'r') as file:
    data = json.load(file)

len(data)

897

In [65]:
[*data.keys()][:10]

['12 (song)',
 '14 May 2026 Russian strikes on Ukraine',
 '15th BRICS summit',
 '16 March 2022 Chernihiv breadline attack',
 '17 November 2024 Russian strikes on Ukraine',
 '18 March 2022 Mykolaiv military quarters attack',
 '1st European Political Community Summit',
 '2000 Meters to Andriivka',
 '2014 pro-Russian unrest in Ukraine',
 '2020s European re-armament']

In [66]:
example = np.random.choice([*data],1)[0]


print(f'PAGE: {example}:\n\n{data[example]}')

PAGE: 2023 Vilnius summit:

The 2023 Vilnius summit was the formal meeting of the heads of state and heads of government of the thirty-one members of the North Atlantic Treaty Organization (NATO), their partner countries, and the European Union, held in Vilnius, Lithuania, on 11–12 July 2023. The summit was officially proposed during the previous 2022 Madrid summit and its dates were fixed on 9 November 2022. It was notable for the discussions about the ongoing Russian invasion of Ukraine as well as Sweden and Ukraine's prospective memberships into the alliance.


== Background ==
The summit was held in the context of an ongoing Russian invasion of Ukraine. In his January 2023 address to the Lithuanian Parliament, President of Ukraine Volodymyr Zelenskyy described the summit as fateful. Ukraine expressed the desire to be formally invited to NATO at the Vilnius summit. On 8 July 2023, US President Joe Biden said that Ukraine is not ready to join NATO at that time. By the time of the summit there were 24 member states that had formally declared their support for Ukraine's NATO membership. Before the summit, on 4 July 2023, the former President of Lithuania Dalia Grybauskaitė criticized the Western leaders who failed to prevent the Russian aggression and said that the refusal to invite Ukraine to NATO would be a mistake.
Following the accession of Finland to NATO earlier in 2023, there had been an expectation among many NATO member states that Turkey and Hungary will complete the ratification process and allow the accession of Sweden before the summit. However, due to Turkish objections, it was unclear if Turkey would support Sweden's application by the time of the summit.
Australia, Japan, New Zealand and South Korea attended the summit to strengthen their ties with NATO due to increasing tensions with China and Russia.


== Security ==

According to a representative of the Dignitary Protection Service of Lithuania, 40 heads of state and up to 150 other high-ranking officials will attend the summit and will require personal protection. To ensure the safety and security, Lithuania committed around 1,500 police officers, including the anti-terrorist unit ARAS and the Criminal Police Bureau, as well as over 3,000 troops of the Lithuanian Armed Forces. Additionally, police officers from Latvia and Poland aided in security and around 1,000 troops from NATO states additionally joined as well, including the Polish Special Forces to aid the Lithuanian Special Operations Force. Overall, up to 12,000 officers and soldiers were deployed. In addition to security personnel, Spain is reported to have temporarily moved its NASAMS air defense system from its long-term position in Latvia to Vilnius, in addition to Lithuania's own NASAMS systems. Similarly, German Armed Forces have deployed their MIM-104 Patriot long-range air defense system, placing it in Vilnius International Airport. NATO sent additional warships to the Baltic Sea. CBRN task force was also deployed.
The Lithuanian State Border Guard Service announced that, from 7 to 13 July, internal Schengen Area border control would be reinstated at Lithuania's border checkpoints with member nations Latvia and Poland, as well as its airports and seaports. For the duration of the event, as well as the days leading up to and after the event, many traffic restrictions were announced by the Vilnius City Municipality, including the closure of the entirety of the Vilnius Old Town and many parts of the city center for vehicles. Additionally, from 11 to 12 July, all flights over Vilnius and the surrounding airspace were prohibited and scheduled flights from Vilnius Airport were suspended. According to a representative of Lithuanian Airports, the other two civilian airports in Lithuania – Kaunas Airport and Palanga Airport – would continue to work but could experience delays.


== Summit ==

US President Joe Biden and a number of other leaders began arriving in Vilnius on Monday, the eve of the summit. In the evening, the Secretary General Jens Stoltenberg hosted a meeting between Turkish President Recep Tayyip Erdoğan and Swedish Prime Minister Ulf Kristersson. Following multiple hours of negotiations, Stoltenberg announced that Erdoğan agreed to unblock Swedish accession to NATO and ensure the ratification as soon as possible. Soon after the announcement, Hungarian Prime Minister, Viktor Orban, stated that Hungary would no longer block the entry of Sweden and would also support their membership into the defence bloc.
On 11 July, the three Baltic States (Estonia, Latvia and Lithuania) signed an agreement on joint airspace defense.
On 11 July, a memorandum was signed between 11 nations and Ukraine to form the F-16 training coalition. As part of the signed memorandum, Ukrainian pilots, technicians, and support personnel will participate in the training program. The coalition consisted of Canada, Belgium, Denmark, Luxembourg, the Netherlands, Norway, Poland, Portugal, Romania, Sweden, and the United Kingdom. According to the US Secretary of Defense Lloyd Austin, Denmark and the Netherlands took leadership of the formed coalition and the two nations are to outline the training plan.
Stoltenberg stated that Ukraine will not become a NATO member while the Russo-Ukrainian War remains ongoing and that the summit was not meant to be a formal invitation for it to join NATO, although countries remain divided on whether Ukraine should be able to join after the war ends. Ukraine's president Volodymyr Zelenskyy said that he wanted NATO to allow Ukraine to join as soon as possible after the war ends. However, other nations feared that such quick admittance of Ukraine to NATO could potentially increase Russian aggression and drag out the war even farther. Stoltenberg has also stated that he expects the summit to create a program of long-term aid over several years for Ukraine: "We have already pledged 500 million euros [US$548m] for critical needs, including fuel, medical supplies, de-mining equipment and pontoon bridges. We will also help build Ukraine's security and defence sector, including with military hospitals. And we will help Ukraine transition from Soviet-era to NATO equipment and standards."
Following the summit, Biden gave a speech at Vilnius University that touched on themes of unity between liberal democracies in the face of Russian aggression.


== Participants ==


== Reactions ==
In a 12 July CNN interview, Boris Johnson, prime minister of the United Kingdom at the onset of the war, criticized the ambiguity about Ukraine's future membership and supported President Biden's decision to send cluster munitions to Ukraine.
British Secretary of Defence Ben Wallace made a remark that "we are not Amazon" and that Ukraine should show more thanks for international military aid. British Prime Minister Rishi Sunak, however, distanced himself from the comment and said that Ukrainians repeatedly expressed the gratitude.


== See also ==
49th G7 summit
Government and intergovernmental reactions to the 2022 Russian invasion of Ukraine


== References ==


== External links ==
Overview – 2023 NATO Summit Vilnius

In [67]:
TITLE = '=='
MIN_LENGTH = 5

paragraphs = data[example].split('\n')
paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]

print(f'{len(paragraphs_processed)} Paragraphs Extracted from {len(paragraphs)}\n{round(len(paragraphs_processed)/len(paragraphs)*100,1)}%')

16 Paragraphs Extracted from 42
38.1%

### Text Preprocessing: Paragraph Filtering

**Purpose:** To perform an initial cleaning of the raw text by filtering out structural elements and short, uninformative lines. This step aims to prepare cleaner text segments for downstream NER processing by removing elements such as section titles and empty or minimal lines.

**Date:** 2026-09-24

In [68]:
TITLE = '=='
MIN_LENGTH = 5

data_processed = {}

total_paragraphs = 0
total_processed = 0

for key, text in data.items():
  paragraphs = text.split('\n')
  paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]
  data_processed[key] = paragraphs_processed

  total_paragraphs += len(paragraphs)
  total_processed += len(paragraphs_processed)

print(f'{total_processed} paragraphs extracted from {total_paragraphs}\n {round(total_processed/total_paragraphs*100,1)}%')

42822 paragraphs extracted from 88029
 48.6%

In [69]:
example = np.random.choice([*data_processed],1)[0]

print(f'PAGE: {example}:\n\n{data_processed[example]}')

PAGE: Oleg Tsokov:

['Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Цоков; 23 September 1971 – 11 July 2023) was a Russian lieutenant general who served in the Russian Ground Forces as deputy commander of the Southern Military District. He was killed in 2023 by a missile strike during a Ukrainian counteroffensive against the Russian invasion of Ukraine.', "Oleg Yuryevich Tsokov was  the son of Yuri Georgievich, a military officer, and Alla Ivanovna, a physicist-mathematician. Since his family moved often, he grew up on military bases and studied at eleven different schools, including in Choibalsan and Semipalatinsk, before receiving his secondary education certificate. Following in his father's footsteps, Tsokov chose a military career and was accepted to the Tashkent Higher Combined Arms Command School. Graduating in 1994, he was posted to the 74th Separate Guards Motor Rifle Brigade at Yurga in the Siberian Military District as a motor rifle platoon commander. Tsokov was deployed to the First Chechen War with the brigade, taking part in the storming of the Grozny Oil Institute during the Battle of Grozny in January 1995. After the end of the battle, Tsokov's unit was sent back to Siberia, but he was sent back to Chechnya for four months as a motor rifle company commander, with his unit attached to a spetsnaz detachment. Tsokov rose to battalion deputy commander with the 74th Brigade before being accepted to the Frunze Military Academy. Graduating in 2000, Tsokov, by then a major, returned to the brigade, fighting in the Second Chechen War that year as commander of a battalion-tactical group formed around the brigade's 2nd Motor Rifle Battalion. He remained battalion commander until 2004, being promoted to lieutenant colonel.", "Tsokov was promoted to colonel and brigade deputy commander in 2004, gaining the rank at the relatively young age of 32. His career continued to advance as he was promoted to command the 228th Motor Rifle Regiment of the 85th Motor Rifle Division in 2006. After his regimental command, he was appointed chief of staff and deputy commander of the 36th Separate Guards Motor Rifle Brigade in the Eastern Military District, serving there from 2009 to 2011. In November 2010, the Investigative Committee of Russia charged Tsokov with committing fraud and abuse of power during his period in command of the 228th Regiment. The case involved a deal in which he illegally promised eleven conscripts early demobilization in return for signing service contracts, then embezzled 80,000 rubles from the soldiers' contract signing bonuses.", 'This case did not affect his career and in 2011 Tsokov was transferred to serve as chief of staff and deputy commander of the 33rd Separate Motor Rifle Brigade of the 49th Combined Arms Army of the Southern Military District, based at Maykop. From 2014 to 2015 he commanded the 810th Separate Naval Infantry Brigade. From 2015 to 2018, he commanded the 205th Separate Motor Rifle Brigade at Budyonnovsk, being promoted to major general on 12 December 2016. From 2018 to 2019, he was deputy commander of the 49th Combined Arms Army. Tsokov passed the exams for the Military Academy of the General Staff, entering the academy in September 2019. After graduating from its national security and state defense department in June 2021, Tsokov was appointed chief of staff of the 2nd Guards Combined Arms Army.', "Tsokov took part in the Russian invasion of Ukraine that began on 24 February 2022. He was involved in missile attacks against Ukrainian cities. In August 2022, he took command of the 144th Guards Motor Rifle Division. In September 2022, Ukrainian presidential spokesman Oleksii Arestovych claimed that Tsokov was wounded while commanding the 144th Guards Motor Rifle Division. A Russian telegram channel confirmed his wounding but stated that Tsokov had in fact commanded the 20th Guards Combined Arms Army since summer 2022, and Tsokov's successor in command of the 144th Division was described as having taken over from Tsokov in summer 2022. Subsequently, Tsokov was promoted to deputy commander of the Southern Military District, and received a promotion to lieutenant general on 17 February 2023. ", "He was killed on 11 July in a strike against the command post of the 58th Combined Arms Army in Berdiansk, during the 2023 Ukrainian counteroffensive. Tsokov's death at age 51 was confirmed by the Russian milblogger telegram channel Military Informer, making him one of the two highest-ranking Russian officers killed in Ukraine as of July 2023. He was buried on 13 July in Maikop.", 'Tsokov was posthumously awarded the title of Hero of the Russian Federation on 19 July 2023.', 'Tsokov received the following decorations:', 'Hero of the Russian Federation', 'Order of Zhukov', 'Order of Courage (3)', 'Order of Military Merit', 'Military operation in Syria medal', 'List of Russian generals killed during the Russian invasion of Ukraine']

In [70]:
SAVE_PATH = '/content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json'

with open(SAVE_PATH, 'w', encoding='utf-8') as f:
    json.dump(data_processed, f, ensure_ascii=False, indent=2)

print(f'Saved to: {SAVE_PATH}')

Saved to: /content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json

## Initial NER application

**Purpose:** To perform an initial NER application with base models and analyze the results

**Date:** 2026-09-24

### DistilBERT

In [71]:
MODEL_DistilBERT = "dslim/distilbert-NER"
MODEL_DistilBERT

ner_DistilBERT = pipeline("ner",
               model=MODEL_DistilBERT,
               aggregation_strategy='average')

ner_DistilBERT

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

TokenClassificationPipeline: {'model': 'DistilBertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [72]:
output_DistilBERT = ner_DistilBERT(data_processed[example])
output_DistilBERT

[[{'entity_group': 'PER',
   'score': np.float32(0.99566525),
   'word': 'Oleg Yuryevich Tsokov',
   'start': 0,
   'end': 21},
  {'entity_group': 'MISC',
   'score': np.float32(0.9325426),
   'word': 'Russian',
   'start': 23,
   'end': 30},
  {'entity_group': 'PER',
   'score': np.float32(0.8685282),
   'word': 'Олег',
   'start': 32,
   'end': 36},
  {'entity_group': 'PER',
   'score': np.float32(0.85478663),
   'word': 'Юрьевич Цоков',
   'start': 37,
   'end': 50},
  {'entity_group': 'MISC',
   'score': np.float32(0.99698824),
   'word': 'Russian',
   'start': 92,
   'end': 99},
  {'entity_group': 'ORG',
   'score': np.float32(0.97474045),
   'word': 'Russian Ground Forces',
   'start': 137,
   'end': 158},
  {'entity_group': 'ORG',
   'score': np.float32(0.8219959),
   'word': 'Southern Military District',
   'start': 186,
   'end': 212},
  {'entity_group': 'MISC',
   'score': np.float32(0.9975473),
   'word': 'Ukrainian',
   'start': 265,
   'end': 274},
  {'entity_group': 'MISC',
   'score': np.float32(0.997551),
   'word': 'Russian',
   'start': 304,
   'end': 311},
  {'entity_group': 'LOC',
   'score': np.float32(0.99781466),
   'word': 'Ukraine',
   'start': 324,
   'end': 331}],
 [{'entity_group': 'PER',
   'score': np.float32(0.99349123),
   'word': 'Oleg Yuryevich Tsokov',
   'start': 0,
   'end': 21},
  {'entity_group': 'PER',
   'score': np.float32(0.9988817),
   'word': 'Yuri Georgievich',
   'start': 38,
   'end': 54},
  {'entity_group': 'PER',
   'score': np.float32(0.9986531),
   'word': 'Alla Ivanovna',
   'start': 80,
   'end': 93},
  {'entity_group': 'LOC',
   'score': np.float32(0.996793),
   'word': 'Choibalsan',
   'start': 235,
   'end': 245},
  {'entity_group': 'LOC',
   'score': np.float32(0.9887813),
   'word': 'Semipalatinsk',
   'start': 250,
   'end': 263},
  {'entity_group': 'PER',
   'score': np.float32(0.9980481),
   'word': 'Tsokov',
   'start': 356,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.61144316),
   'word': 'Tashkent',
   'start': 411,
   'end': 419},
  {'entity_group': 'ORG',
   'score': np.float32(0.748849),
   'word': 'Higher Combined Arms Command School',
   'start': 420,
   'end': 455},
  {'entity_group': 'ORG',
   'score': np.float32(0.9322916),
   'word': 'Separate Guards Motor Rifle Brigade',
   'start': 503,
   'end': 538},
  {'entity_group': 'LOC',
   'score': np.float32(0.9950744),
   'word': 'Yurga',
   'start': 542,
   'end': 547},
  {'entity_group': 'LOC',
   'score': np.float32(0.97018594),
   'word': 'Siberian Military District',
   'start': 555,
   'end': 581},
  {'entity_group': 'PER',
   'score': np.float32(0.9971948),
   'word': 'Tsokov',
   'start': 618,
   'end': 624},
  {'entity_group': 'MISC',
   'score': np.float32(0.9863002),
   'word': 'First Chechen War',
   'start': 645,
   'end': 662},
  {'entity_group': 'LOC',
   'score': np.float32(0.9750376),
   'word': 'Grozny Oil Institute',
   'start': 716,
   'end': 736},
  {'entity_group': 'LOC',
   'score': np.float32(0.35336006),
   'word': 'of',
   'start': 755,
   'end': 757},
  {'entity_group': 'LOC',
   'score': np.float32(0.9196638),
   'word': 'Grozny',
   'start': 758,
   'end': 764},
  {'entity_group': 'PER',
   'score': np.float32(0.99767786),
   'word': 'Tsokov',
   'start': 811,
   'end': 817},
  {'entity_group': 'LOC',
   'score': np.float32(0.99881184),
   'word': 'Siberia',
   'start': 842,
   'end': 849},
  {'entity_group': 'LOC',
   'score': np.float32(0.9980602),
   'word': 'Chechnya',
   'start': 875,
   'end': 883},
  {'entity_group': 'PER',
   'score': np.float32(0.9954652),
   'word': 'Tsokov',
   'start': 985,
   'end': 991},
  {'entity_group': 'ORG',
   'score': np.float32(0.5745204),
   'word': 'Brigade',
   'start': 1041,
   'end': 1048},
  {'entity_group': 'ORG',
   'score': np.float32(0.87256384),
   'word': 'Frunze Military Academy',
   'start': 1078,
   'end': 1101},
  {'entity_group': 'PER',
   'score': np.float32(0.9983484),
   'word': 'Tsokov',
   'start': 1123,
   'end': 1129},
  {'entity_group': 'MISC',
   'score': np.float32(0.982457),
   'word': 'Second Chechen War',
   'start': 1189,
   'end': 1207},
  {'entity_group': 'ORG',
   'score': np.float32(0.83767265),
   'word': 'Motor Rifle Battalion',
   'start': 1293,
   'end': 1314}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9978609),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'ORG',
   'score': np.float32(0.9348903),
   'word': 'Motor Rifle Regiment',
   'start': 193,
   'end': 213},
  {'entity_group': 'ORG',
   'score': np.float32(0.86962825),
   'word': 'Motor Rifle Division',
   'start': 226,
   'end': 246},
  {'entity_group': 'ORG',
   'score': np.float32(0.8949503),
   'word': 'Separate Guards Motor Rifle Brigade',
   'start': 351,
   'end': 386},
  {'entity_group': 'LOC',
   'score': np.float32(0.91609675),
   'word': 'Eastern Military District',
   'start': 394,
   'end': 419},
  {'entity_group': 'ORG',
   'score': np.float32(0.8944382),
   'word': 'Investigative Committee of Russia',
   'start': 476,
   'end': 509},
  {'entity_group': 'PER',
   'score': np.float32(0.99793977),
   'word': 'Tsokov',
   'start': 518,
   'end': 524},
  {'entity_group': 'ORG',
   'score': np.float32(0.8062147),
   'word': 'Regiment',
   'start': 608,
   'end': 616}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9897623),
   'word': 'Tsokov',
   'start': 48,
   'end': 54},
  {'entity_group': 'ORG',
   'score': np.float32(0.7989167),
   'word': 'Separate Motor Rifle Brigade',
   'start': 131,
   'end': 159},
  {'entity_group': 'ORG',
   'score': np.float32(0.9690659),
   'word': 'Combined Arms Army',
   'start': 172,
   'end': 190},
  {'entity_group': 'LOC',
   'score': np.float32(0.93193007),
   'word': 'Southern',
   'start': 198,
   'end': 206},
  {'entity_group': 'ORG',
   'score': np.float32(0.67022425),
   'word': 'Military District',
   'start': 207,
   'end': 224},
  {'entity_group': 'LOC',
   'score': np.float32(0.9965605),
   'word': 'Maykop',
   'start': 235,
   'end': 241},
  {'entity_group': 'ORG',
   'score': np.float32(0.7885389),
   'word': 'Separate Naval Infantry Brigade',
   'start': 284,
   'end': 315},
  {'entity_group': 'ORG',
   'score': np.float32(0.8012109),
   'word': 'Separate Motor Rifle Brigade',
   'start': 359,
   'end': 387},
  {'entity_group': 'LOC',
   'score': np.float32(0.9976636),
   'word': 'Budyonnovsk',
   'start': 391,
   'end': 402},
  {'entity_group': 'ORG',
   'score': np.float32(0.94213563),
   'word': 'Combined Arms Army',
   'start': 512,
   'end': 530},
  {'entity_group': 'PER',
   'score': np.float32(0.98937863),
   'word': 'Tsokov',
   'start': 532,
   'end': 538},
  {'entity_group': 'ORG',
   'score': np.float32(0.9280265),
   'word': 'Military Academy of the General Staff',
   'start': 564,
   'end': 601},
  {'entity_group': 'PER',
   'score': np.float32(0.9887946),
   'word': 'Tsokov',
   'start': 730,
   'end': 736},
  {'entity_group': 'ORG',
   'score': np.float32(0.9641063),
   'word': 'Guards Combined Arms Army',
   'start': 777,
   'end': 802}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9971886),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'MISC',
   'score': np.float32(0.99783295),
   'word': 'Russian',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.9964856),
   'word': 'Ukraine',
   'start': 44,
   'end': 51},
  {'entity_group': 'MISC',
   'score': np.float32(0.991105),
   'word': 'Ukrainian',
   'start': 127,
   'end': 136},
  {'entity_group': 'ORG',
   'score': np.float32(0.8524693),
   'word': 'Guards Motor Rifle Division',
   'start': 190,
   'end': 217},
  {'entity_group': 'MISC',
   'score': np.float32(0.9972427),
   'word': 'Ukrainian',
   'start': 238,
   'end': 247},
  {'entity_group': 'PER',
   'score': np.float32(0.9991324),
   'word': 'Oleksii Arestovych',
   'start': 271,
   'end': 289},
  {'entity_group': 'PER',
   'score': np.float32(0.9983681),
   'word': 'Tsokov',
   'start': 303,
   'end': 309},
  {'entity_group': 'ORG',
   'score': np.float32(0.9182914),
   'word': 'Guards Motor Rifle Division',
   'start': 349,
   'end': 376},
  {'entity_group': 'MISC',
   'score': np.float32(0.98951846),
   'word': 'Russian',
   'start': 380,
   'end': 387},
  {'entity_group': 'PER',
   'score': np.float32(0.9980183),
   'word': 'Tsokov',
   'start': 444,
   'end': 450},
  {'entity_group': 'ORG',
   'score': np.float32(0.94738173),
   'word': 'Guards Combined Arms Army',
   'start': 482,
   'end': 507},
  {'entity_group': 'PER',
   'score': np.float32(0.9985674),
   'word': 'Tsokov',
   'start': 531,
   'end': 537},
  {'entity_group': 'ORG',
   'score': np.float32(0.7178539),
   'word': 'Division',
   'start': 574,
   'end': 582},
  {'entity_group': 'PER',
   'score': np.float32(0.99849063),
   'word': 'Tsokov',
   'start': 623,
   'end': 629},
  {'entity_group': 'PER',
   'score': np.float32(0.9980707),
   'word': 'Tsokov',
   'start': 660,
   'end': 666},
  {'entity_group': 'LOC',
   'score': np.float32(0.73552585),
   'word': 'Southern Military',
   'start': 707,
   'end': 724},
  {'entity_group': 'ORG',
   'score': np.float32(0.529476),
   'word': 'District',
   'start': 725,
   'end': 733}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.93900937),
   'word': 'Combined Arms Army',
   'start': 74,
   'end': 92},
  {'entity_group': 'LOC',
   'score': np.float32(0.99810696),
   'word': 'Berdiansk',
   'start': 96,
   'end': 105},
  {'entity_group': 'MISC',
   'score': np.float32(0.9977335),
   'word': 'Ukrainian',
   'start': 123,
   'end': 132},
  {'entity_group': 'PER',
   'score': np.float32(0.99898577),
   'word': 'Tsokov',
   'start': 151,
   'end': 157},
  {'entity_group': 'MISC',
   'score': np.float32(0.99451196),
   'word': 'Russian',
   'start': 197,
   'end': 204},
  {'entity_group': 'ORG',
   'score': np.float32(0.90710217),
   'word': 'Military Informer',
   'start': 233,
   'end': 250},
  {'entity_group': 'MISC',
   'score': np.float32(0.99785525),
   'word': 'Russian',
   'start': 294,
   'end': 301},
  {'entity_group': 'LOC',
   'score': np.float32(0.9990177),
   'word': 'Ukraine',
   'start': 321,
   'end': 328},
  {'entity_group': 'LOC',
   'score': np.float32(0.9967995),
   'word': 'Maikop',
   'start': 374,
   'end': 380}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9982366),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'LOC',
   'score': np.float32(0.8833952),
   'word': 'Russian Federation',
   'start': 57,
   'end': 75}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9989051),
   'word': 'Tsokov',
   'start': 0,
   'end': 6}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.7932216),
   'word': 'Russian Federation',
   'start': 12,
   'end': 30}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.27254483),
   'word': 'Zhukov',
   'start': 9,
   'end': 15}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.48050666),
   'word': 'of Courage',
   'start': 6,
   'end': 16}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.37793294),
   'word': 'Military',
   'start': 9,
   'end': 17},
  {'entity_group': 'MISC',
   'score': np.float32(0.5919782),
   'word': 'Merit',
   'start': 18,
   'end': 23}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9975605),
   'word': 'Syria',
   'start': 22,
   'end': 27}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9953359),
   'word': 'Russian',
   'start': 8,
   'end': 15},
  {'entity_group': 'MISC',
   'score': np.float32(0.99657047),
   'word': 'Russian',
   'start': 43,
   'end': 50},
  {'entity_group': 'LOC',
   'score': np.float32(0.99394035),
   'word': 'Ukraine',
   'start': 63,
   'end': 70}]]

In [78]:
df_DistilBERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_DistilBERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.995665,Oleg Yuryevich Tsokov,0,21
1,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,MISC,0.932543,Russian,23,30
2,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.868528,Олег,32,36
3,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.854787,Юрьевич Цоков,37,50
4,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,MISC,0.996988,Russian,92,99
...,...,...,...,...,...,...,...,...
91,Oleg Tsokov,11,Order of Military Merit,MISC,0.591978,Merit,18,23
92,Oleg Tsokov,12,Military operation in Syria medal,LOC,0.997561,Syria,22,27
93,Oleg Tsokov,13,List of Russian generals killed during the Rus...,MISC,0.995336,Russian,8,15
94,Oleg Tsokov,13,List of Russian generals killed during the Rus...,MISC,0.996570,Russian,43,50
95,Oleg Tsokov,13,List of Russian generals killed during the Rus...,LOC,0.993940,Ukraine,63,70

### BERT

In [74]:
MODEL_BERT = "dslim/bert-base-NER"
MODEL_BERT

ner_BERT = pipeline("ner",
               model=MODEL_BERT,
               aggregation_strategy='average')

ner_BERT

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

TokenClassificationPipeline: {'model': 'BertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [75]:
output_BERT = ner_BERT(data_processed[example])
output_BERT

[[{'entity_group': 'PER',
   'score': np.float32(0.9833424),
   'word': 'Oleg Yuryevich Tsokov',
   'start': 0,
   'end': 21},
  {'entity_group': 'MISC',
   'score': np.float32(0.9988771),
   'word': 'Russian',
   'start': 23,
   'end': 30},
  {'entity_group': 'PER',
   'score': np.float32(0.9521918),
   'word': 'Олег Юрьевич',
   'start': 32,
   'end': 44},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997689),
   'word': 'Russian',
   'start': 92,
   'end': 99},
  {'entity_group': 'ORG',
   'score': np.float32(0.9957163),
   'word': 'Russian Ground Forces',
   'start': 137,
   'end': 158},
  {'entity_group': 'LOC',
   'score': np.float32(0.4995426),
   'word': 'Southern',
   'start': 186,
   'end': 194},
  {'entity_group': 'ORG',
   'score': np.float32(0.8658221),
   'word': 'Military',
   'start': 195,
   'end': 203},
  {'entity_group': 'LOC',
   'score': np.float32(0.7493531),
   'word': 'District',
   'start': 204,
   'end': 212},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997427),
   'word': 'Ukrainian',
   'start': 265,
   'end': 274},
  {'entity_group': 'MISC',
   'score': np.float32(0.99976796),
   'word': 'Russian',
   'start': 304,
   'end': 311},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997824),
   'word': 'Ukraine',
   'start': 324,
   'end': 331}],
 [{'entity_group': 'PER',
   'score': np.float32(0.9033975),
   'word': 'Oleg Yuryevich Tsokov',
   'start': 0,
   'end': 21},
  {'entity_group': 'PER',
   'score': np.float32(0.98524135),
   'word': 'Yuri Georgievich',
   'start': 38,
   'end': 54},
  {'entity_group': 'PER',
   'score': np.float32(0.7613114),
   'word': 'Alla Ivanovna',
   'start': 80,
   'end': 93},
  {'entity_group': 'LOC',
   'score': np.float32(0.65619034),
   'word': 'Choibalsan',
   'start': 235,
   'end': 245},
  {'entity_group': 'LOC',
   'score': np.float32(0.7631339),
   'word': 'Semipalatinsk',
   'start': 250,
   'end': 263},
  {'entity_group': 'PER',
   'score': np.float32(0.7182109),
   'word': 'Tsokov',
   'start': 356,
   'end': 362},
  {'entity_group': 'ORG',
   'score': np.float32(0.7969664),
   'word': 'Tashkent Higher Combined Arms Command School',
   'start': 411,
   'end': 455},
  {'entity_group': 'ORG',
   'score': np.float32(0.9108067),
   'word': '74th Separate Guards Motor Rifle Brigade',
   'start': 498,
   'end': 538},
  {'entity_group': 'LOC',
   'score': np.float32(0.5003323),
   'word': 'Yurga',
   'start': 542,
   'end': 547},
  {'entity_group': 'LOC',
   'score': np.float32(0.9927456),
   'word': 'Siberian Military District',
   'start': 555,
   'end': 581},
  {'entity_group': 'PER',
   'score': np.float32(0.70229465),
   'word': 'Tsokov',
   'start': 618,
   'end': 624},
  {'entity_group': 'MISC',
   'score': np.float32(0.9968557),
   'word': 'First Chechen War',
   'start': 645,
   'end': 662},
  {'entity_group': 'LOC',
   'score': np.float32(0.556392),
   'word': 'Grozny',
   'start': 716,
   'end': 722},
  {'entity_group': 'ORG',
   'score': np.float32(0.6478785),
   'word': 'Oil Institute',
   'start': 723,
   'end': 736},
  {'entity_group': 'MISC',
   'score': np.float32(0.5578667),
   'word': 'Battle of',
   'start': 748,
   'end': 757},
  {'entity_group': 'LOC',
   'score': np.float32(0.7421502),
   'word': 'Grozny',
   'start': 758,
   'end': 764},
  {'entity_group': 'PER',
   'score': np.float32(0.6418561),
   'word': 'Tsokov',
   'start': 811,
   'end': 817},
  {'entity_group': 'LOC',
   'score': np.float32(0.999691),
   'word': 'Siberia',
   'start': 842,
   'end': 849},
  {'entity_group': 'LOC',
   'score': np.float32(0.66474146),
   'word': 'Chechnya',
   'start': 875,
   'end': 883},
  {'entity_group': 'PER',
   'score': np.float32(0.6709359),
   'word': 'Tsokov',
   'start': 985,
   'end': 991},
  {'entity_group': 'ORG',
   'score': np.float32(0.7416246),
   'word': '74th Brigade',
   'start': 1036,
   'end': 1048},
  {'entity_group': 'ORG',
   'score': np.float32(0.83961385),
   'word': 'Frunze Military Academy',
   'start': 1078,
   'end': 1101},
  {'entity_group': 'PER',
   'score': np.float32(0.6712665),
   'word': 'Tsokov',
   'start': 1123,
   'end': 1129},
  {'entity_group': 'MISC',
   'score': np.float32(0.99585944),
   'word': 'Second Chechen War',
   'start': 1189,
   'end': 1207},
  {'entity_group': 'ORG',
   'score': np.float32(0.9717062),
   'word': '2nd Motor Rifle Battalion',
   'start': 1289,
   'end': 1314}],
 [{'entity_group': 'PER',
   'score': np.float32(0.73766893),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'ORG',
   'score': np.float32(0.87144417),
   'word': '228th Motor Rifle Regiment',
   'start': 187,
   'end': 213},
  {'entity_group': 'ORG',
   'score': np.float32(0.87197006),
   'word': '85th Motor Rifle Division',
   'start': 221,
   'end': 246},
  {'entity_group': 'ORG',
   'score': np.float32(0.99721617),
   'word': '36th Separate Guards Motor Rifle Brigade',
   'start': 346,
   'end': 386},
  {'entity_group': 'LOC',
   'score': np.float32(0.957218),
   'word': 'Eastern Military District',
   'start': 394,
   'end': 419},
  {'entity_group': 'ORG',
   'score': np.float32(0.9033135),
   'word': 'Investigative Committee of Russia',
   'start': 476,
   'end': 509},
  {'entity_group': 'PER',
   'score': np.float32(0.8209887),
   'word': 'Tsokov',
   'start': 518,
   'end': 524},
  {'entity_group': 'ORG',
   'score': np.float32(0.73534304),
   'word': '228th Regiment',
   'start': 602,
   'end': 616}],
 [{'entity_group': 'PER',
   'score': np.float32(0.72397727),
   'word': 'Tsokov',
   'start': 48,
   'end': 54},
  {'entity_group': 'ORG',
   'score': np.float32(0.99739426),
   'word': '33rd Separate Motor Rifle Brigade',
   'start': 126,
   'end': 159},
  {'entity_group': 'ORG',
   'score': np.float32(0.8832137),
   'word': '49th Combined Arms Army of',
   'start': 167,
   'end': 193},
  {'entity_group': 'LOC',
   'score': np.float32(0.5874796),
   'word': 'Southern',
   'start': 198,
   'end': 206},
  {'entity_group': 'ORG',
   'score': np.float32(0.9867157),
   'word': 'Military District',
   'start': 207,
   'end': 224},
  {'entity_group': 'LOC',
   'score': np.float32(0.56725603),
   'word': 'Maykop',
   'start': 235,
   'end': 241},
  {'entity_group': 'ORG',
   'score': np.float32(0.8833044),
   'word': '810th Separate Naval Infantry Brigade',
   'start': 278,
   'end': 315},
  {'entity_group': 'ORG',
   'score': np.float32(0.8976406),
   'word': '205th Separate Motor Rifle Brigade',
   'start': 353,
   'end': 387},
  {'entity_group': 'LOC',
   'score': np.float32(0.73903763),
   'word': 'Budyonnovsk',
   'start': 391,
   'end': 402},
  {'entity_group': 'ORG',
   'score': np.float32(0.88018346),
   'word': '49th Combined Arms Army',
   'start': 507,
   'end': 530},
  {'entity_group': 'PER',
   'score': np.float32(0.692399),
   'word': 'Tsokov',
   'start': 532,
   'end': 538},
  {'entity_group': 'ORG',
   'score': np.float32(0.9980827),
   'word': 'Military Academy of the General Staff',
   'start': 564,
   'end': 601},
  {'entity_group': 'PER',
   'score': np.float32(0.6241659),
   'word': 'Tsokov',
   'start': 730,
   'end': 736},
  {'entity_group': 'ORG',
   'score': np.float32(0.9972509),
   'word': '2nd Guards Combined Arms Army',
   'start': 773,
   'end': 802}],
 [{'entity_group': 'PER',
   'score': np.float32(0.7375739),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997665),
   'word': 'Russian',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.99973565),
   'word': 'Ukraine',
   'start': 44,
   'end': 51},
  {'entity_group': 'MISC',
   'score': np.float32(0.99974686),
   'word': 'Ukrainian',
   'start': 127,
   'end': 136},
  {'entity_group': 'ORG',
   'score': np.float32(0.8962391),
   'word': '144th Guards Motor Rifle Division',
   'start': 184,
   'end': 217},
  {'entity_group': 'MISC',
   'score': np.float32(0.999724),
   'word': 'Ukrainian',
   'start': 238,
   'end': 247},
  {'entity_group': 'PER',
   'score': np.float32(0.9283793),
   'word': 'Oleksii Arestovych',
   'start': 271,
   'end': 289},
  {'entity_group': 'PER',
   'score': np.float32(0.7126507),
   'word': 'Tsokov',
   'start': 303,
   'end': 309},
  {'entity_group': 'ORG',
   'score': np.float32(0.89500856),
   'word': '144th Guards Motor Rifle Division',
   'start': 343,
   'end': 376},
  {'entity_group': 'MISC',
   'score': np.float32(0.99978703),
   'word': 'Russian',
   'start': 380,
   'end': 387},
  {'entity_group': 'PER',
   'score': np.float32(0.7172641),
   'word': 'Tsokov',
   'start': 444,
   'end': 450},
  {'entity_group': 'ORG',
   'score': np.float32(0.99784315),
   'word': '20th Guards Combined Arms Army',
   'start': 477,
   'end': 507},
  {'entity_group': 'PER',
   'score': np.float32(0.6800869),
   'word': 'Tsokov',
   'start': 531,
   'end': 537},
  {'entity_group': 'ORG',
   'score': np.float32(0.74170494),
   'word': '144th Division',
   'start': 568,
   'end': 582},
  {'entity_group': 'PER',
   'score': np.float32(0.8279466),
   'word': 'Tsokov',
   'start': 623,
   'end': 629},
  {'entity_group': 'PER',
   'score': np.float32(0.6650477),
   'word': 'Tsokov',
   'start': 660,
   'end': 666},
  {'entity_group': 'LOC',
   'score': np.float32(0.6934596),
   'word': 'Southern',
   'start': 707,
   'end': 715},
  {'entity_group': 'ORG',
   'score': np.float32(0.6525028),
   'word': 'Military',
   'start': 716,
   'end': 724},
  {'entity_group': 'LOC',
   'score': np.float32(0.85796636),
   'word': 'District',
   'start': 725,
   'end': 733}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9820201),
   'word': 'Combined Arms Army',
   'start': 74,
   'end': 92},
  {'entity_group': 'LOC',
   'score': np.float32(0.5095979),
   'word': 'Berdiansk',
   'start': 96,
   'end': 105},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997079),
   'word': 'Ukrainian',
   'start': 123,
   'end': 132},
  {'entity_group': 'PER',
   'score': np.float32(0.7035599),
   'word': 'Tsokov',
   'start': 151,
   'end': 157},
  {'entity_group': 'MISC',
   'score': np.float32(0.99969673),
   'word': 'Russian',
   'start': 197,
   'end': 204},
  {'entity_group': 'ORG',
   'score': np.float32(0.99454015),
   'word': 'Military Informer',
   'start': 233,
   'end': 250},
  {'entity_group': 'MISC',
   'score': np.float32(0.99976975),
   'word': 'Russian',
   'start': 294,
   'end': 301},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997955),
   'word': 'Ukraine',
   'start': 321,
   'end': 328},
  {'entity_group': 'LOC',
   'score': np.float32(0.6629812),
   'word': 'Maikop',
   'start': 374,
   'end': 380}],
 [{'entity_group': 'PER',
   'score': np.float32(0.87173706),
   'word': 'Tsokov',
   'start': 0,
   'end': 6},
  {'entity_group': 'MISC',
   'score': np.float32(0.82661486),
   'word': 'Hero of the',
   'start': 45,
   'end': 56},
  {'entity_group': 'LOC',
   'score': np.float32(0.997034),
   'word': 'Russian Federation',
   'start': 57,
   'end': 75}],
 [{'entity_group': 'PER',
   'score': np.float32(0.8668215),
   'word': 'Tsokov',
   'start': 0,
   'end': 6}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.995929),
   'word': 'Russian Federation',
   'start': 12,
   'end': 30}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.6501788),
   'word': 'Order of',
   'start': 0,
   'end': 8},
  {'entity_group': 'MISC',
   'score': np.float32(0.67359185),
   'word': 'Zhukov',
   'start': 9,
   'end': 15}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.67568254),
   'word': 'Order',
   'start': 0,
   'end': 5},
  {'entity_group': 'MISC',
   'score': np.float32(0.8198898),
   'word': 'of Courage',
   'start': 6,
   'end': 16}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.8624416),
   'word': 'Order of Military Merit',
   'start': 0,
   'end': 23}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9997304),
   'word': 'Syria',
   'start': 22,
   'end': 27}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9996594),
   'word': 'Russian',
   'start': 8,
   'end': 15},
  {'entity_group': 'MISC',
   'score': np.float32(0.99969566),
   'word': 'Russian',
   'start': 43,
   'end': 50},
  {'entity_group': 'LOC',
   'score': np.float32(0.99981266),
   'word': 'Ukraine',
   'start': 63,
   'end': 70}]]

In [79]:
df_BERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_BERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.995665,Oleg Yuryevich Tsokov,0,21
1,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,MISC,0.932543,Russian,23,30
2,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.868528,Олег,32,36
3,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,PER,0.854787,Юрьевич Цоков,37,50
4,Oleg Tsokov,0,Oleg Yuryevich Tsokov (Russian: Олег Юрьевич Ц...,MISC,0.996988,Russian,92,99
...,...,...,...,...,...,...,...,...
91,Oleg Tsokov,11,Order of Military Merit,MISC,0.591978,Merit,18,23
92,Oleg Tsokov,12,Military operation in Syria medal,LOC,0.997561,Syria,22,27
93,Oleg Tsokov,13,List of Russian generals killed during the Rus...,MISC,0.995336,Russian,8,15
94,Oleg Tsokov,13,List of Russian generals killed during the Rus...,MISC,0.996570,Russian,43,50
95,Oleg Tsokov,13,List of Russian generals killed during the Rus...,LOC,0.993940,Ukraine,63,70

## Commit to repo

In [77]:
REPO_PATH = "/content/Corpus2GeoRAG"
GITHUB_USER = "idoschw3"
GITHUB_REPO = "Corpus2GeoRAG"
GITHUB_EMAIL = "193781032+idoschw3@users.noreply.github.com"
COMMIT_MESSAGE = "Update NER workflow"

# Move to repository
os.chdir(REPO_PATH)

# Set Git identity for this repository
subprocess.run(["git", "config", "user.name", GITHUB_USER], check=True)
subprocess.run(["git", "config", "user.email", GITHUB_EMAIL], check=True)

# Make sure origin points to my personal fork
subprocess.run([
    "git", "remote", "set-url", "origin",
    f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}.git"
], check=True)

# Stage ALL new, modified, and deleted files
subprocess.run(["git", "add", "-A"], check=True)

# Commit only if there are changes
status = subprocess.run(
    ["git", "status", "--porcelain"],
    capture_output=True,
    text=True,
    check=True
)

if status.stdout.strip():
    subprocess.run(
        ["git", "commit", "-m", COMMIT_MESSAGE],
        check=True
    )
    print("Changes committed.")
else:
    print("No new changes to commit.")

# Read GitHub token securely from Colab Secrets
github_token = userdata.get("GITHUB_TOKEN")

# Temporary authentication helper
askpass_path = "/tmp/github_askpass.sh"

with open(askpass_path, "w") as f:
    f.write(
        '#!/bin/sh\n'
        'case "$1" in\n'
        '  *Username*) echo "$GITHUB_USER" ;;\n'
        '  *Password*) echo "$GITHUB_TOKEN" ;;\n'
        'esac\n'
    )

os.chmod(askpass_path, 0o700)

env = os.environ.copy()
env["GITHUB_USER"] = GITHUB_USER
env["GITHUB_TOKEN"] = github_token
env["GIT_ASKPASS"] = askpass_path
env["GIT_TERMINAL_PROMPT"] = "0"

# Push the current branch to my fork
branch = subprocess.run(
    ["git", "branch", "--show-current"],
    capture_output=True,
    text=True,
    check=True
).stdout.strip()

try:
    subprocess.run(
        ["git", "push", "origin", branch],
        env=env,
        check=True
    )
    print(f"Successfully pushed to {GITHUB_USER}/{GITHUB_REPO} on branch '{branch}'.")
finally:
    if os.path.exists(askpass_path):
        os.remove(askpass_path)

No new changes to commit.
Successfully pushed to idoschw3/Corpus2GeoRAG on branch 'main'.